package com.xunge.model.selfelec;

import java.util.Date;

public class EleBillaccountbaseresource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccountbaseresource.billaccountbaseresource_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private String billaccountbaseresourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccountbaseresource.billaccount_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private String billaccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccountbaseresource.baseresource_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private String baseresourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccountbaseresource.relation_state
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private Integer relationState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccountbaseresource.relation_startdate
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private Date relationStartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccountbaseresource.relation_enddate
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private Date relationEnddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccountbaseresource.billaccountbaseresource_id
     *
     * @return the value of ele_billaccountbaseresource.billaccountbaseresource_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public String getBillaccountbaseresourceId() {
        return billaccountbaseresourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccountbaseresource.billaccountbaseresource_id
     *
     * @param billaccountbaseresourceId the value for ele_billaccountbaseresource.billaccountbaseresource_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setBillaccountbaseresourceId(String billaccountbaseresourceId) {
        this.billaccountbaseresourceId = billaccountbaseresourceId == null ? null : billaccountbaseresourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccountbaseresource.billaccount_id
     *
     * @return the value of ele_billaccountbaseresource.billaccount_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public String getBillaccountId() {
        return billaccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccountbaseresource.billaccount_id
     *
     * @param billaccountId the value for ele_billaccountbaseresource.billaccount_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setBillaccountId(String billaccountId) {
        this.billaccountId = billaccountId == null ? null : billaccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccountbaseresource.baseresource_id
     *
     * @return the value of ele_billaccountbaseresource.baseresource_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public String getBaseresourceId() {
        return baseresourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccountbaseresource.baseresource_id
     *
     * @param baseresourceId the value for ele_billaccountbaseresource.baseresource_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setBaseresourceId(String baseresourceId) {
        this.baseresourceId = baseresourceId == null ? null : baseresourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccountbaseresource.relation_state
     *
     * @return the value of ele_billaccountbaseresource.relation_state
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public Integer getRelationState() {
        return relationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccountbaseresource.relation_state
     *
     * @param relationState the value for ele_billaccountbaseresource.relation_state
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setRelationState(Integer relationState) {
        this.relationState = relationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccountbaseresource.relation_startdate
     *
     * @return the value of ele_billaccountbaseresource.relation_startdate
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public Date getRelationStartdate() {
        return relationStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccountbaseresource.relation_startdate
     *
     * @param relationStartdate the value for ele_billaccountbaseresource.relation_startdate
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setRelationStartdate(Date relationStartdate) {
        this.relationStartdate = relationStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccountbaseresource.relation_enddate
     *
     * @return the value of ele_billaccountbaseresource.relation_enddate
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public Date getRelationEnddate() {
        return relationEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccountbaseresource.relation_enddate
     *
     * @param relationEnddate the value for ele_billaccountbaseresource.relation_enddate
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setRelationEnddate(Date relationEnddate) {
        this.relationEnddate = relationEnddate;
    }
}