package com.xunge.model.selfelec;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.xunge.model.activity.Act;

public class EleBillaccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.billaccount_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private String billaccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.preg_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private String pregId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.preg_name
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private String pregName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.reg_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.reg_name
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private String regName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.billaccount_code
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private String billaccountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.billaccount_name
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private String billaccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.billaccount_state
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private Integer billaccountState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.billaccount_type
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private Integer billaccountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.plan_date
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private Date planDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.calc_multi
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private BigDecimal calcMulti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.auditing_state
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private Integer auditingState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.auditing_user_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private String auditingUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.auditing_date
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private Date auditingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount.billaccount_note
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    private String billaccountNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.billaccount_id
     *
     * @return the value of ele_billaccount.billaccount_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public String getBillaccountId() {
        return billaccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.billaccount_id
     *
     * @param billaccountId the value for ele_billaccount.billaccount_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setBillaccountId(String billaccountId) {
        this.billaccountId = billaccountId == null ? null : billaccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.preg_id
     *
     * @return the value of ele_billaccount.preg_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public String getPregId() {
        return pregId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.preg_id
     *
     * @param pregId the value for ele_billaccount.preg_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setPregId(String pregId) {
        this.pregId = pregId == null ? null : pregId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.preg_name
     *
     * @return the value of ele_billaccount.preg_name
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public String getPregName() {
        return pregName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.preg_name
     *
     * @param pregName the value for ele_billaccount.preg_name
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setPregName(String pregName) {
        this.pregName = pregName == null ? null : pregName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.reg_id
     *
     * @return the value of ele_billaccount.reg_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.reg_id
     *
     * @param regId the value for ele_billaccount.reg_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.reg_name
     *
     * @return the value of ele_billaccount.reg_name
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public String getRegName() {
        return regName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.reg_name
     *
     * @param regName the value for ele_billaccount.reg_name
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setRegName(String regName) {
        this.regName = regName == null ? null : regName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.billaccount_code
     *
     * @return the value of ele_billaccount.billaccount_code
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public String getBillaccountCode() {
        return billaccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.billaccount_code
     *
     * @param billaccountCode the value for ele_billaccount.billaccount_code
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setBillaccountCode(String billaccountCode) {
        this.billaccountCode = billaccountCode == null ? null : billaccountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.billaccount_name
     *
     * @return the value of ele_billaccount.billaccount_name
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public String getBillaccountName() {
        return billaccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.billaccount_name
     *
     * @param billaccountName the value for ele_billaccount.billaccount_name
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setBillaccountName(String billaccountName) {
        this.billaccountName = billaccountName == null ? null : billaccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.billaccount_state
     *
     * @return the value of ele_billaccount.billaccount_state
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public Integer getBillaccountState() {
        return billaccountState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.billaccount_state
     *
     * @param billaccountState the value for ele_billaccount.billaccount_state
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setBillaccountState(Integer billaccountState) {
        this.billaccountState = billaccountState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.billaccount_type
     *
     * @return the value of ele_billaccount.billaccount_type
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public Integer getBillaccountType() {
        return billaccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.billaccount_type
     *
     * @param billaccountType the value for ele_billaccount.billaccount_type
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setBillaccountType(Integer billaccountType) {
        this.billaccountType = billaccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.plan_date
     *
     * @return the value of ele_billaccount.plan_date
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getPlanDate() {
        return planDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.plan_date
     *
     * @param planDate the value for ele_billaccount.plan_date
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setPlanDate(Date planDate) {
        this.planDate = planDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.calc_multi
     *
     * @return the value of ele_billaccount.calc_multi
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public BigDecimal getCalcMulti() {
        return calcMulti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.calc_multi
     *
     * @param calcMulti the value for ele_billaccount.calc_multi
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setCalcMulti(BigDecimal calcMulti) {
        this.calcMulti = calcMulti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.auditing_state
     *
     * @return the value of ele_billaccount.auditing_state
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public Integer getAuditingState() {
        return auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.auditing_state
     *
     * @param auditingState the value for ele_billaccount.auditing_state
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setAuditingState(Integer auditingState) {
        this.auditingState = auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.auditing_user_id
     *
     * @return the value of ele_billaccount.auditing_user_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public String getAuditingUserId() {
        return auditingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.auditing_user_id
     *
     * @param auditingUserId the value for ele_billaccount.auditing_user_id
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setAuditingUserId(String auditingUserId) {
        this.auditingUserId = auditingUserId == null ? null : auditingUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.auditing_date
     *
     * @return the value of ele_billaccount.auditing_date
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss") 
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8") 
    public Date getAuditingDate() {
        return auditingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.auditing_date
     *
     * @param auditingDate the value for ele_billaccount.auditing_date
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setAuditingDate(Date auditingDate) {
        this.auditingDate = auditingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount.billaccount_note
     *
     * @return the value of ele_billaccount.billaccount_note
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public String getBillaccountNote() {
        return billaccountNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount.billaccount_note
     *
     * @param billaccountNote the value for ele_billaccount.billaccount_note
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    public void setBillaccountNote(String billaccountNote) {
        this.billaccountNote = billaccountNote == null ? null : billaccountNote.trim();
    }
    
    public Act getAct() {
		return act;
	}

	public void setAct(Act act) {
		this.act = act;
	}

	private Act act;
}