package com.xunge.model.selfelec;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class EleBillaccountPaymentdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.billaccountpaymentdetail_id
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private String billaccountpaymentdetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.billaccount_id
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private String billamountId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.billaccount_id
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private String billaccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.billamount_startdate
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Date billamountStartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.billamount_enddate
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Date billamountEnddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.billamount_date
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Date billamountDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.buy_method
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Integer buyMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.payment_method
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Integer paymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.bill_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Integer billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.invoice_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Integer invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.tax_payment_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Integer taxPaymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.is_vat_deduction
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Integer isVatDeduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.business_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Integer businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.amount_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Integer amountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.billamount_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Integer billamountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.billamount_notax_sys
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private BigDecimal billamountNotaxSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.billamount_notax
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private BigDecimal billamountNotax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.loss_amount_sys
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private BigDecimal lossAmountSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.loss_amount
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private BigDecimal lossAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.billamount_taxamount_sys
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private BigDecimal billamountTaxamountSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.billamount_taxamount
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private BigDecimal billamountTaxamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.other_amount
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private BigDecimal otherAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.bill_amount_sys
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private BigDecimal billAmountSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.bill_amount_actual
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private BigDecimal billAmountActual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.total_degree
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private BigDecimal totalDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.calc_multi
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private BigDecimal calcMulti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.total_degree_actual
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private BigDecimal totalDegreeActual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.submit_state
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Integer submitState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.auditing_state
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Integer auditingState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.auditing_user_id
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private String auditingUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.auditing_date
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private Date auditingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_billaccount_paymentdetail.paymentdetail_note
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    private String paymentdetailNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.billaccountpaymentdetail_id
     *
     * @return the value of ele_billaccount_paymentdetail.billaccountpaymentdetail_id
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public String getBillaccountpaymentdetailId() {
        return billaccountpaymentdetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.billaccountpaymentdetail_id
     *
     * @param billaccountpaymentdetailId the value for ele_billaccount_paymentdetail.billaccountpaymentdetail_id
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillaccountpaymentdetailId(String billaccountpaymentdetailId) {
        this.billaccountpaymentdetailId = billaccountpaymentdetailId == null ? null : billaccountpaymentdetailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.billaccount_id
     *
     * @return the value of ele_billaccount_paymentdetail.billaccount_id
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public String getBillaccountId() {
        return billaccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.billaccount_id
     *
     * @param billaccountId the value for ele_billaccount_paymentdetail.billaccount_id
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillaccountId(String billaccountId) {
        this.billaccountId = billaccountId == null ? null : billaccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.billamount_startdate
     *
     * @return the value of ele_billaccount_paymentdetail.billamount_startdate
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getBillamountStartdate() {
        return billamountStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.billamount_startdate
     *
     * @param billamountStartdate the value for ele_billaccount_paymentdetail.billamount_startdate
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillamountStartdate(Date billamountStartdate) {
        this.billamountStartdate = billamountStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.billamount_enddate
     *
     * @return the value of ele_billaccount_paymentdetail.billamount_enddate
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getBillamountEnddate() {
        return billamountEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.billamount_enddate
     *
     * @param billamountEnddate the value for ele_billaccount_paymentdetail.billamount_enddate
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillamountEnddate(Date billamountEnddate) {
        this.billamountEnddate = billamountEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.billamount_date
     *
     * @return the value of ele_billaccount_paymentdetail.billamount_date
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getBillamountDate() {
        return billamountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.billamount_date
     *
     * @param billamountDate the value for ele_billaccount_paymentdetail.billamount_date
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillamountDate(Date billamountDate) {
        this.billamountDate = billamountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.buy_method
     *
     * @return the value of ele_billaccount_paymentdetail.buy_method
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public Integer getBuyMethod() {
        return buyMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.buy_method
     *
     * @param buyMethod the value for ele_billaccount_paymentdetail.buy_method
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBuyMethod(Integer buyMethod) {
        this.buyMethod = buyMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.payment_method
     *
     * @return the value of ele_billaccount_paymentdetail.payment_method
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public Integer getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.payment_method
     *
     * @param paymentMethod the value for ele_billaccount_paymentdetail.payment_method
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setPaymentMethod(Integer paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.bill_type
     *
     * @return the value of ele_billaccount_paymentdetail.bill_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public Integer getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.bill_type
     *
     * @param billType the value for ele_billaccount_paymentdetail.bill_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillType(Integer billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.invoice_type
     *
     * @return the value of ele_billaccount_paymentdetail.invoice_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public Integer getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.invoice_type
     *
     * @param invoiceType the value for ele_billaccount_paymentdetail.invoice_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setInvoiceType(Integer invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.tax_payment_type
     *
     * @return the value of ele_billaccount_paymentdetail.tax_payment_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public Integer getTaxPaymentType() {
        return taxPaymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.tax_payment_type
     *
     * @param taxPaymentType the value for ele_billaccount_paymentdetail.tax_payment_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setTaxPaymentType(Integer taxPaymentType) {
        this.taxPaymentType = taxPaymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.is_vat_deduction
     *
     * @return the value of ele_billaccount_paymentdetail.is_vat_deduction
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public Integer getIsVatDeduction() {
        return isVatDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.is_vat_deduction
     *
     * @param isVatDeduction the value for ele_billaccount_paymentdetail.is_vat_deduction
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setIsVatDeduction(Integer isVatDeduction) {
        this.isVatDeduction = isVatDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.business_type
     *
     * @return the value of ele_billaccount_paymentdetail.business_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.business_type
     *
     * @param businessType the value for ele_billaccount_paymentdetail.business_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.amount_type
     *
     * @return the value of ele_billaccount_paymentdetail.amount_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public Integer getAmountType() {
        return amountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.amount_type
     *
     * @param amountType the value for ele_billaccount_paymentdetail.amount_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setAmountType(Integer amountType) {
        this.amountType = amountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.billamount_type
     *
     * @return the value of ele_billaccount_paymentdetail.billamount_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public Integer getBillamountType() {
        return billamountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.billamount_type
     *
     * @param billamountType the value for ele_billaccount_paymentdetail.billamount_type
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillamountType(Integer billamountType) {
        this.billamountType = billamountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.billamount_notax_sys
     *
     * @return the value of ele_billaccount_paymentdetail.billamount_notax_sys
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public BigDecimal getBillamountNotaxSys() {
        return billamountNotaxSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.billamount_notax_sys
     *
     * @param billamountNotaxSys the value for ele_billaccount_paymentdetail.billamount_notax_sys
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillamountNotaxSys(BigDecimal billamountNotaxSys) {
        this.billamountNotaxSys = billamountNotaxSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.billamount_notax
     *
     * @return the value of ele_billaccount_paymentdetail.billamount_notax
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public BigDecimal getBillamountNotax() {
        return billamountNotax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.billamount_notax
     *
     * @param billamountNotax the value for ele_billaccount_paymentdetail.billamount_notax
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillamountNotax(BigDecimal billamountNotax) {
        this.billamountNotax = billamountNotax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.loss_amount_sys
     *
     * @return the value of ele_billaccount_paymentdetail.loss_amount_sys
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public BigDecimal getLossAmountSys() {
        return lossAmountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.loss_amount_sys
     *
     * @param lossAmountSys the value for ele_billaccount_paymentdetail.loss_amount_sys
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setLossAmountSys(BigDecimal lossAmountSys) {
        this.lossAmountSys = lossAmountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.loss_amount
     *
     * @return the value of ele_billaccount_paymentdetail.loss_amount
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public BigDecimal getLossAmount() {
        return lossAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.loss_amount
     *
     * @param lossAmount the value for ele_billaccount_paymentdetail.loss_amount
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setLossAmount(BigDecimal lossAmount) {
        this.lossAmount = lossAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.billamount_taxamount_sys
     *
     * @return the value of ele_billaccount_paymentdetail.billamount_taxamount_sys
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public BigDecimal getBillamountTaxamountSys() {
        return billamountTaxamountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.billamount_taxamount_sys
     *
     * @param billamountTaxamountSys the value for ele_billaccount_paymentdetail.billamount_taxamount_sys
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillamountTaxamountSys(BigDecimal billamountTaxamountSys) {
        this.billamountTaxamountSys = billamountTaxamountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.billamount_taxamount
     *
     * @return the value of ele_billaccount_paymentdetail.billamount_taxamount
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public BigDecimal getBillamountTaxamount() {
        return billamountTaxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.billamount_taxamount
     *
     * @param billamountTaxamount the value for ele_billaccount_paymentdetail.billamount_taxamount
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillamountTaxamount(BigDecimal billamountTaxamount) {
        this.billamountTaxamount = billamountTaxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.other_amount
     *
     * @return the value of ele_billaccount_paymentdetail.other_amount
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public BigDecimal getOtherAmount() {
        return otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.other_amount
     *
     * @param otherAmount the value for ele_billaccount_paymentdetail.other_amount
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setOtherAmount(BigDecimal otherAmount) {
        this.otherAmount = otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.bill_amount_sys
     *
     * @return the value of ele_billaccount_paymentdetail.bill_amount_sys
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public BigDecimal getBillAmountSys() {
        return billAmountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.bill_amount_sys
     *
     * @param billAmountSys the value for ele_billaccount_paymentdetail.bill_amount_sys
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillAmountSys(BigDecimal billAmountSys) {
        this.billAmountSys = billAmountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.bill_amount_actual
     *
     * @return the value of ele_billaccount_paymentdetail.bill_amount_actual
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public BigDecimal getBillAmountActual() {
        return billAmountActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.bill_amount_actual
     *
     * @param billAmountActual the value for ele_billaccount_paymentdetail.bill_amount_actual
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setBillAmountActual(BigDecimal billAmountActual) {
        this.billAmountActual = billAmountActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.total_degree
     *
     * @return the value of ele_billaccount_paymentdetail.total_degree
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public BigDecimal getTotalDegree() {
        return totalDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.total_degree
     *
     * @param totalDegree the value for ele_billaccount_paymentdetail.total_degree
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setTotalDegree(BigDecimal totalDegree) {
        this.totalDegree = totalDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.calc_multi
     *
     * @return the value of ele_billaccount_paymentdetail.calc_multi
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public BigDecimal getCalcMulti() {
        return calcMulti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.calc_multi
     *
     * @param calcMulti the value for ele_billaccount_paymentdetail.calc_multi
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setCalcMulti(BigDecimal calcMulti) {
        this.calcMulti = calcMulti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.total_degree_actual
     *
     * @return the value of ele_billaccount_paymentdetail.total_degree_actual
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public BigDecimal getTotalDegreeActual() {
        return totalDegreeActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.total_degree_actual
     *
     * @param totalDegreeActual the value for ele_billaccount_paymentdetail.total_degree_actual
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setTotalDegreeActual(BigDecimal totalDegreeActual) {
        this.totalDegreeActual = totalDegreeActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.submit_state
     *
     * @return the value of ele_billaccount_paymentdetail.submit_state
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public Integer getSubmitState() {
        return submitState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.submit_state
     *
     * @param submitState the value for ele_billaccount_paymentdetail.submit_state
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setSubmitState(Integer submitState) {
        this.submitState = submitState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.auditing_state
     *
     * @return the value of ele_billaccount_paymentdetail.auditing_state
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public Integer getAuditingState() {
        return auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.auditing_state
     *
     * @param auditingState the value for ele_billaccount_paymentdetail.auditing_state
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setAuditingState(Integer auditingState) {
        this.auditingState = auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.auditing_user_id
     *
     * @return the value of ele_billaccount_paymentdetail.auditing_user_id
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public String getAuditingUserId() {
        return auditingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.auditing_user_id
     *
     * @param auditingUserId the value for ele_billaccount_paymentdetail.auditing_user_id
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setAuditingUserId(String auditingUserId) {
        this.auditingUserId = auditingUserId == null ? null : auditingUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.auditing_date
     *
     * @return the value of ele_billaccount_paymentdetail.auditing_date
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getAuditingDate() {
        return auditingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.auditing_date
     *
     * @param auditingDate the value for ele_billaccount_paymentdetail.auditing_date
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setAuditingDate(Date auditingDate) {
        this.auditingDate = auditingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_billaccount_paymentdetail.paymentdetail_note
     *
     * @return the value of ele_billaccount_paymentdetail.paymentdetail_note
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public String getPaymentdetailNote() {
        return paymentdetailNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_billaccount_paymentdetail.paymentdetail_note
     *
     * @param paymentdetailNote the value for ele_billaccount_paymentdetail.paymentdetail_note
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    public void setPaymentdetailNote(String paymentdetailNote) {
        this.paymentdetailNote = paymentdetailNote == null ? null : paymentdetailNote.trim();
    }

	public String getBillamountId() {
		return billamountId;
	}

	public void setBillamountId(String billamountId) {
		this.billamountId = billamountId;
	}
	
	public String getPaymentUserId() {
		return paymentUserId;
	}

	public void setPaymentUserId(String paymentUserId) {
		this.paymentUserId = paymentUserId;
	}

	private String paymentUserId;
}