package com.xunge.model.selfelec;

public class VDatElectricmeterBr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_electricmeter_br.meter_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String meterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_electricmeter_br.baseresource_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String baseresourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_electricmeter_br.baseresource_code
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String baseresourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_electricmeter_br.baseresource_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String baseresourceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_electricmeter_br.meter_id
     *
     * @return the value of v_dat_electricmeter_br.meter_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getMeterId() {
        return meterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_electricmeter_br.meter_id
     *
     * @param meterId the value for v_dat_electricmeter_br.meter_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setMeterId(String meterId) {
        this.meterId = meterId == null ? null : meterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_electricmeter_br.baseresource_id
     *
     * @return the value of v_dat_electricmeter_br.baseresource_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getBaseresourceId() {
        return baseresourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_electricmeter_br.baseresource_id
     *
     * @param baseresourceId the value for v_dat_electricmeter_br.baseresource_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceId(String baseresourceId) {
        this.baseresourceId = baseresourceId == null ? null : baseresourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_electricmeter_br.baseresource_code
     *
     * @return the value of v_dat_electricmeter_br.baseresource_code
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getBaseresourceCode() {
        return baseresourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_electricmeter_br.baseresource_code
     *
     * @param baseresourceCode the value for v_dat_electricmeter_br.baseresource_code
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceCode(String baseresourceCode) {
        this.baseresourceCode = baseresourceCode == null ? null : baseresourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_electricmeter_br.baseresource_name
     *
     * @return the value of v_dat_electricmeter_br.baseresource_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getBaseresourceName() {
        return baseresourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_electricmeter_br.baseresource_name
     *
     * @param baseresourceName the value for v_dat_electricmeter_br.baseresource_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceName(String baseresourceName) {
        this.baseresourceName = baseresourceName == null ? null : baseresourceName.trim();
    }
}