package com.xunge.model.selfelec;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.xunge.model.selfelec.electricmeter.DatElectricMeterVO;

public class VDatBaseresource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String baseresourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.basesite_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String basesiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.prv_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String prvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.prv_sname
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String prvSname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.preg_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String pregId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.preg_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String pregName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.reg_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.reg_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String regName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_type
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private Integer baseresourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_category
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private Integer baseresourceCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_cuid
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String baseresourceCuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_code
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String baseresourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String baseresourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_address
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String baseresourceAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_area
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private BigDecimal baseresourceArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_maintenance
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private Integer baseresourceMaintenance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.tower_site_code
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String towerSiteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_opendate
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private Date baseresourceOpendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_stopdate
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private Date baseresourceStopdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.room_owner
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private Integer roomOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.room_property
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private Integer roomProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.room_share
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private Integer roomShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_longitude
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private BigDecimal baseresourceLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_latitude
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private BigDecimal baseresourceLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.airconditioner_power
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private BigDecimal airconditionerPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_state
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private Integer baseresourceState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.baseresource_note
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String baseresourceNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.auditing_state
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private Integer auditingState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.auditing_user_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String auditingUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.auditing_date
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private Date auditingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.data_from
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private Integer dataFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.basesite_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String basesiteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_dat_baseresource.user_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_id
     *
     * @return the value of v_dat_baseresource.baseresource_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getBaseresourceId() {
        return baseresourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_id
     *
     * @param baseresourceId the value for v_dat_baseresource.baseresource_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceId(String baseresourceId) {
        this.baseresourceId = baseresourceId == null ? null : baseresourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.basesite_id
     *
     * @return the value of v_dat_baseresource.basesite_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getBasesiteId() {
        return basesiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.basesite_id
     *
     * @param basesiteId the value for v_dat_baseresource.basesite_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBasesiteId(String basesiteId) {
        this.basesiteId = basesiteId == null ? null : basesiteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.prv_id
     *
     * @return the value of v_dat_baseresource.prv_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getPrvId() {
        return prvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.prv_id
     *
     * @param prvId the value for v_dat_baseresource.prv_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setPrvId(String prvId) {
        this.prvId = prvId == null ? null : prvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.prv_sname
     *
     * @return the value of v_dat_baseresource.prv_sname
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getPrvSname() {
        return prvSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.prv_sname
     *
     * @param prvSname the value for v_dat_baseresource.prv_sname
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setPrvSname(String prvSname) {
        this.prvSname = prvSname == null ? null : prvSname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.preg_id
     *
     * @return the value of v_dat_baseresource.preg_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getPregId() {
        return pregId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.preg_id
     *
     * @param pregId the value for v_dat_baseresource.preg_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setPregId(String pregId) {
        this.pregId = pregId == null ? null : pregId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.preg_name
     *
     * @return the value of v_dat_baseresource.preg_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getPregName() {
        return pregName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.preg_name
     *
     * @param pregName the value for v_dat_baseresource.preg_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setPregName(String pregName) {
        this.pregName = pregName == null ? null : pregName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.reg_id
     *
     * @return the value of v_dat_baseresource.reg_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.reg_id
     *
     * @param regId the value for v_dat_baseresource.reg_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.reg_name
     *
     * @return the value of v_dat_baseresource.reg_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getRegName() {
        return regName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.reg_name
     *
     * @param regName the value for v_dat_baseresource.reg_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setRegName(String regName) {
        this.regName = regName == null ? null : regName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_type
     *
     * @return the value of v_dat_baseresource.baseresource_type
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public Integer getBaseresourceType() {
        return baseresourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_type
     *
     * @param baseresourceType the value for v_dat_baseresource.baseresource_type
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceType(Integer baseresourceType) {
        this.baseresourceType = baseresourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_category
     *
     * @return the value of v_dat_baseresource.baseresource_category
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public Integer getBaseresourceCategory() {
        return baseresourceCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_category
     *
     * @param baseresourceCategory the value for v_dat_baseresource.baseresource_category
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceCategory(Integer baseresourceCategory) {
        this.baseresourceCategory = baseresourceCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_cuid
     *
     * @return the value of v_dat_baseresource.baseresource_cuid
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getBaseresourceCuid() {
        return baseresourceCuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_cuid
     *
     * @param baseresourceCuid the value for v_dat_baseresource.baseresource_cuid
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceCuid(String baseresourceCuid) {
        this.baseresourceCuid = baseresourceCuid == null ? null : baseresourceCuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_code
     *
     * @return the value of v_dat_baseresource.baseresource_code
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getBaseresourceCode() {
        return baseresourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_code
     *
     * @param baseresourceCode the value for v_dat_baseresource.baseresource_code
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceCode(String baseresourceCode) {
        this.baseresourceCode = baseresourceCode == null ? null : baseresourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_name
     *
     * @return the value of v_dat_baseresource.baseresource_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getBaseresourceName() {
        return baseresourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_name
     *
     * @param baseresourceName the value for v_dat_baseresource.baseresource_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceName(String baseresourceName) {
        this.baseresourceName = baseresourceName == null ? null : baseresourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_address
     *
     * @return the value of v_dat_baseresource.baseresource_address
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getBaseresourceAddress() {
        return baseresourceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_address
     *
     * @param baseresourceAddress the value for v_dat_baseresource.baseresource_address
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceAddress(String baseresourceAddress) {
        this.baseresourceAddress = baseresourceAddress == null ? null : baseresourceAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_area
     *
     * @return the value of v_dat_baseresource.baseresource_area
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public BigDecimal getBaseresourceArea() {
        return baseresourceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_area
     *
     * @param baseresourceArea the value for v_dat_baseresource.baseresource_area
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceArea(BigDecimal baseresourceArea) {
        this.baseresourceArea = baseresourceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_maintenance
     *
     * @return the value of v_dat_baseresource.baseresource_maintenance
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public Integer getBaseresourceMaintenance() {
        return baseresourceMaintenance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_maintenance
     *
     * @param baseresourceMaintenance the value for v_dat_baseresource.baseresource_maintenance
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceMaintenance(Integer baseresourceMaintenance) {
        this.baseresourceMaintenance = baseresourceMaintenance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.tower_site_code
     *
     * @return the value of v_dat_baseresource.tower_site_code
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getTowerSiteCode() {
        return towerSiteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.tower_site_code
     *
     * @param towerSiteCode the value for v_dat_baseresource.tower_site_code
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setTowerSiteCode(String towerSiteCode) {
        this.towerSiteCode = towerSiteCode == null ? null : towerSiteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_opendate
     *
     * @return the value of v_dat_baseresource.baseresource_opendate
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public Date getBaseresourceOpendate() {
        return baseresourceOpendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_opendate
     *
     * @param baseresourceOpendate the value for v_dat_baseresource.baseresource_opendate
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceOpendate(Date baseresourceOpendate) {
        this.baseresourceOpendate = baseresourceOpendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_stopdate
     *
     * @return the value of v_dat_baseresource.baseresource_stopdate
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public Date getBaseresourceStopdate() {
        return baseresourceStopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_stopdate
     *
     * @param baseresourceStopdate the value for v_dat_baseresource.baseresource_stopdate
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceStopdate(Date baseresourceStopdate) {
        this.baseresourceStopdate = baseresourceStopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.room_owner
     *
     * @return the value of v_dat_baseresource.room_owner
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public Integer getRoomOwner() {
        return roomOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.room_owner
     *
     * @param roomOwner the value for v_dat_baseresource.room_owner
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setRoomOwner(Integer roomOwner) {
        this.roomOwner = roomOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.room_property
     *
     * @return the value of v_dat_baseresource.room_property
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public Integer getRoomProperty() {
        return roomProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.room_property
     *
     * @param roomProperty the value for v_dat_baseresource.room_property
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setRoomProperty(Integer roomProperty) {
        this.roomProperty = roomProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.room_share
     *
     * @return the value of v_dat_baseresource.room_share
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public Integer getRoomShare() {
        return roomShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.room_share
     *
     * @param roomShare the value for v_dat_baseresource.room_share
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setRoomShare(Integer roomShare) {
        this.roomShare = roomShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_longitude
     *
     * @return the value of v_dat_baseresource.baseresource_longitude
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public BigDecimal getBaseresourceLongitude() {
        return baseresourceLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_longitude
     *
     * @param baseresourceLongitude the value for v_dat_baseresource.baseresource_longitude
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceLongitude(BigDecimal baseresourceLongitude) {
        this.baseresourceLongitude = baseresourceLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_latitude
     *
     * @return the value of v_dat_baseresource.baseresource_latitude
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public BigDecimal getBaseresourceLatitude() {
        return baseresourceLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_latitude
     *
     * @param baseresourceLatitude the value for v_dat_baseresource.baseresource_latitude
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceLatitude(BigDecimal baseresourceLatitude) {
        this.baseresourceLatitude = baseresourceLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.airconditioner_power
     *
     * @return the value of v_dat_baseresource.airconditioner_power
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public BigDecimal getAirconditionerPower() {
        return airconditionerPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.airconditioner_power
     *
     * @param airconditionerPower the value for v_dat_baseresource.airconditioner_power
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setAirconditionerPower(BigDecimal airconditionerPower) {
        this.airconditionerPower = airconditionerPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_state
     *
     * @return the value of v_dat_baseresource.baseresource_state
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public Integer getBaseresourceState() {
        return baseresourceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_state
     *
     * @param baseresourceState the value for v_dat_baseresource.baseresource_state
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceState(Integer baseresourceState) {
        this.baseresourceState = baseresourceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.baseresource_note
     *
     * @return the value of v_dat_baseresource.baseresource_note
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getBaseresourceNote() {
        return baseresourceNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.baseresource_note
     *
     * @param baseresourceNote the value for v_dat_baseresource.baseresource_note
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBaseresourceNote(String baseresourceNote) {
        this.baseresourceNote = baseresourceNote == null ? null : baseresourceNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.auditing_state
     *
     * @return the value of v_dat_baseresource.auditing_state
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public Integer getAuditingState() {
        return auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.auditing_state
     *
     * @param auditingState the value for v_dat_baseresource.auditing_state
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setAuditingState(Integer auditingState) {
        this.auditingState = auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.auditing_user_id
     *
     * @return the value of v_dat_baseresource.auditing_user_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getAuditingUserId() {
        return auditingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.auditing_user_id
     *
     * @param auditingUserId the value for v_dat_baseresource.auditing_user_id
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setAuditingUserId(String auditingUserId) {
        this.auditingUserId = auditingUserId == null ? null : auditingUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.auditing_date
     *
     * @return the value of v_dat_baseresource.auditing_date
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public Date getAuditingDate() {
        return auditingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.auditing_date
     *
     * @param auditingDate the value for v_dat_baseresource.auditing_date
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setAuditingDate(Date auditingDate) {
        this.auditingDate = auditingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.data_from
     *
     * @return the value of v_dat_baseresource.data_from
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public Integer getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.data_from
     *
     * @param dataFrom the value for v_dat_baseresource.data_from
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setDataFrom(Integer dataFrom) {
        this.dataFrom = dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.basesite_name
     *
     * @return the value of v_dat_baseresource.basesite_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getBasesiteName() {
        return basesiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.basesite_name
     *
     * @param basesiteName the value for v_dat_baseresource.basesite_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setBasesiteName(String basesiteName) {
        this.basesiteName = basesiteName == null ? null : basesiteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_dat_baseresource.user_name
     *
     * @return the value of v_dat_baseresource.user_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_dat_baseresource.user_name
     *
     * @param userName the value for v_dat_baseresource.user_name
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
    
  	public List<DatElectricMeterVO> getElectricMeterVO() {
		return electricMeterVO;
	}

	public void setElectricMeterVO(List<DatElectricMeterVO> electricMeterVO) {
		this.electricMeterVO = electricMeterVO;
	}

	private List<DatElectricMeterVO> electricMeterVO;
}