package com.xunge.model.selfelec;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class VEleBillaccountcontract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.elecontract_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String elecontractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.supplier_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.paymentperiod_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String paymentperiodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.price_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer priceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.elecontract_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String elecontractPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.include_price_tax
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer includePriceTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.flat_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal flatPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.peak_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal peakPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.valley_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal valleyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.top_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal topPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.supply_method
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer supplyMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.buy_method
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer buyMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.payment_method
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer paymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.include_tax
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer includeTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.tax_rate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal taxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.is_include_all
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer isIncludeAll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.pay_sign
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer paySign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.pay_sign_account
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal paySignAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_money
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal contractMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_tax
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal contractTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_total_amount
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal contractTotalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_year_amount
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal contractYearAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.independent_meter
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer independentMeter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.cmcc_ratio
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal cmccRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.unicom_ratio
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal unicomRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.telcom_ratio
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal telcomRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.include_loss
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer includeLoss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.loss_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer lossType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.payment_user
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String paymentUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.payment_telphone
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String paymentTelphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.elecontract_note
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String elecontractNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.prv_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String prvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.prv_sname
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String prvSname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.preg_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String pregId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.preg_name
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String pregName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.reg_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.reg_name
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String regName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.is_downshare
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer isDownshare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.sys_dep_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String sysDepId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.manager_department
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String managerDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.user_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_code
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String contractCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_name
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer contractType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_startdate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Date contractStartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_enddate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Date contractEnddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_signdate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Date contractSigndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_yearquantity
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private BigDecimal contractYearquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_checkname1
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String contractCheckname1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_checkname2
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String contractCheckname2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.old_contract_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String oldContractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.old_contract_code
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String oldContractCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_flow
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String contractFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_introduction
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String contractIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_spaceresource
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String contractSpaceresource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_state
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer contractState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.contract_note
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String contractNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.auditing_state
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer auditingState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.auditing_user_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String auditingUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.auditing_date
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Date auditingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.data_from
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer dataFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.supplier_code
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.supplier_name
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.supplier_address
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String supplierAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.supplier_contact
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String supplierContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.supplier_telephone
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String supplierTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.supplier_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer supplierType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.account_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.bank_user
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String bankUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.deposit_bank
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String depositBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.bank_account
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.supplier_state
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer supplierState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.supplier_note
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String supplierNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.elebillaccountcontract_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String elebillaccountcontractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.billaccount_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private String billaccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.relation_state
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Integer relationState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.relation_startdate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Date relationStartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccountcontract.relation_enddate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    private Date relationEnddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.elecontract_id
     *
     * @return the value of v_ele_billaccountcontract.elecontract_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getElecontractId() {
        return elecontractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.elecontract_id
     *
     * @param elecontractId the value for v_ele_billaccountcontract.elecontract_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setElecontractId(String elecontractId) {
        this.elecontractId = elecontractId == null ? null : elecontractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_id
     *
     * @return the value of v_ele_billaccountcontract.contract_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_id
     *
     * @param contractId the value for v_ele_billaccountcontract.contract_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractId(String contractId) {
        this.contractId = contractId == null ? null : contractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.supplier_id
     *
     * @return the value of v_ele_billaccountcontract.supplier_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.supplier_id
     *
     * @param supplierId the value for v_ele_billaccountcontract.supplier_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId == null ? null : supplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.paymentperiod_id
     *
     * @return the value of v_ele_billaccountcontract.paymentperiod_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getPaymentperiodId() {
        return paymentperiodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.paymentperiod_id
     *
     * @param paymentperiodId the value for v_ele_billaccountcontract.paymentperiod_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setPaymentperiodId(String paymentperiodId) {
        this.paymentperiodId = paymentperiodId == null ? null : paymentperiodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.price_type
     *
     * @return the value of v_ele_billaccountcontract.price_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getPriceType() {
        return priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.price_type
     *
     * @param priceType the value for v_ele_billaccountcontract.price_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setPriceType(Integer priceType) {
        this.priceType = priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.elecontract_price
     *
     * @return the value of v_ele_billaccountcontract.elecontract_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getElecontractPrice() {
        return elecontractPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.elecontract_price
     *
     * @param elecontractPrice the value for v_ele_billaccountcontract.elecontract_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setElecontractPrice(String elecontractPrice) {
        this.elecontractPrice = elecontractPrice == null ? null : elecontractPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.include_price_tax
     *
     * @return the value of v_ele_billaccountcontract.include_price_tax
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getIncludePriceTax() {
        return includePriceTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.include_price_tax
     *
     * @param includePriceTax the value for v_ele_billaccountcontract.include_price_tax
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setIncludePriceTax(Integer includePriceTax) {
        this.includePriceTax = includePriceTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.flat_price
     *
     * @return the value of v_ele_billaccountcontract.flat_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getFlatPrice() {
        return flatPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.flat_price
     *
     * @param flatPrice the value for v_ele_billaccountcontract.flat_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setFlatPrice(BigDecimal flatPrice) {
        this.flatPrice = flatPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.peak_price
     *
     * @return the value of v_ele_billaccountcontract.peak_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getPeakPrice() {
        return peakPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.peak_price
     *
     * @param peakPrice the value for v_ele_billaccountcontract.peak_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setPeakPrice(BigDecimal peakPrice) {
        this.peakPrice = peakPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.valley_price
     *
     * @return the value of v_ele_billaccountcontract.valley_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getValleyPrice() {
        return valleyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.valley_price
     *
     * @param valleyPrice the value for v_ele_billaccountcontract.valley_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setValleyPrice(BigDecimal valleyPrice) {
        this.valleyPrice = valleyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.top_price
     *
     * @return the value of v_ele_billaccountcontract.top_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getTopPrice() {
        return topPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.top_price
     *
     * @param topPrice the value for v_ele_billaccountcontract.top_price
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setTopPrice(BigDecimal topPrice) {
        this.topPrice = topPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.supply_method
     *
     * @return the value of v_ele_billaccountcontract.supply_method
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getSupplyMethod() {
        return supplyMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.supply_method
     *
     * @param supplyMethod the value for v_ele_billaccountcontract.supply_method
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setSupplyMethod(Integer supplyMethod) {
        this.supplyMethod = supplyMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.buy_method
     *
     * @return the value of v_ele_billaccountcontract.buy_method
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getBuyMethod() {
        return buyMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.buy_method
     *
     * @param buyMethod the value for v_ele_billaccountcontract.buy_method
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setBuyMethod(Integer buyMethod) {
        this.buyMethod = buyMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.payment_method
     *
     * @return the value of v_ele_billaccountcontract.payment_method
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.payment_method
     *
     * @param paymentMethod the value for v_ele_billaccountcontract.payment_method
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setPaymentMethod(Integer paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.include_tax
     *
     * @return the value of v_ele_billaccountcontract.include_tax
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getIncludeTax() {
        return includeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.include_tax
     *
     * @param includeTax the value for v_ele_billaccountcontract.include_tax
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setIncludeTax(Integer includeTax) {
        this.includeTax = includeTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.tax_rate
     *
     * @return the value of v_ele_billaccountcontract.tax_rate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.tax_rate
     *
     * @param taxRate the value for v_ele_billaccountcontract.tax_rate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setTaxRate(BigDecimal taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.is_include_all
     *
     * @return the value of v_ele_billaccountcontract.is_include_all
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getIsIncludeAll() {
        return isIncludeAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.is_include_all
     *
     * @param isIncludeAll the value for v_ele_billaccountcontract.is_include_all
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setIsIncludeAll(Integer isIncludeAll) {
        this.isIncludeAll = isIncludeAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.pay_sign
     *
     * @return the value of v_ele_billaccountcontract.pay_sign
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getPaySign() {
        return paySign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.pay_sign
     *
     * @param paySign the value for v_ele_billaccountcontract.pay_sign
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setPaySign(Integer paySign) {
        this.paySign = paySign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.pay_sign_account
     *
     * @return the value of v_ele_billaccountcontract.pay_sign_account
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getPaySignAccount() {
        return paySignAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.pay_sign_account
     *
     * @param paySignAccount the value for v_ele_billaccountcontract.pay_sign_account
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setPaySignAccount(BigDecimal paySignAccount) {
        this.paySignAccount = paySignAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_money
     *
     * @return the value of v_ele_billaccountcontract.contract_money
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getContractMoney() {
        return contractMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_money
     *
     * @param contractMoney the value for v_ele_billaccountcontract.contract_money
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractMoney(BigDecimal contractMoney) {
        this.contractMoney = contractMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_tax
     *
     * @return the value of v_ele_billaccountcontract.contract_tax
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getContractTax() {
        return contractTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_tax
     *
     * @param contractTax the value for v_ele_billaccountcontract.contract_tax
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractTax(BigDecimal contractTax) {
        this.contractTax = contractTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_total_amount
     *
     * @return the value of v_ele_billaccountcontract.contract_total_amount
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getContractTotalAmount() {
        return contractTotalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_total_amount
     *
     * @param contractTotalAmount the value for v_ele_billaccountcontract.contract_total_amount
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractTotalAmount(BigDecimal contractTotalAmount) {
        this.contractTotalAmount = contractTotalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_year_amount
     *
     * @return the value of v_ele_billaccountcontract.contract_year_amount
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getContractYearAmount() {
        return contractYearAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_year_amount
     *
     * @param contractYearAmount the value for v_ele_billaccountcontract.contract_year_amount
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractYearAmount(BigDecimal contractYearAmount) {
        this.contractYearAmount = contractYearAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.independent_meter
     *
     * @return the value of v_ele_billaccountcontract.independent_meter
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getIndependentMeter() {
        return independentMeter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.independent_meter
     *
     * @param independentMeter the value for v_ele_billaccountcontract.independent_meter
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setIndependentMeter(Integer independentMeter) {
        this.independentMeter = independentMeter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.cmcc_ratio
     *
     * @return the value of v_ele_billaccountcontract.cmcc_ratio
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getCmccRatio() {
        return cmccRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.cmcc_ratio
     *
     * @param cmccRatio the value for v_ele_billaccountcontract.cmcc_ratio
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setCmccRatio(BigDecimal cmccRatio) {
        this.cmccRatio = cmccRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.unicom_ratio
     *
     * @return the value of v_ele_billaccountcontract.unicom_ratio
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getUnicomRatio() {
        return unicomRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.unicom_ratio
     *
     * @param unicomRatio the value for v_ele_billaccountcontract.unicom_ratio
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setUnicomRatio(BigDecimal unicomRatio) {
        this.unicomRatio = unicomRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.telcom_ratio
     *
     * @return the value of v_ele_billaccountcontract.telcom_ratio
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getTelcomRatio() {
        return telcomRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.telcom_ratio
     *
     * @param telcomRatio the value for v_ele_billaccountcontract.telcom_ratio
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setTelcomRatio(BigDecimal telcomRatio) {
        this.telcomRatio = telcomRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.include_loss
     *
     * @return the value of v_ele_billaccountcontract.include_loss
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getIncludeLoss() {
        return includeLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.include_loss
     *
     * @param includeLoss the value for v_ele_billaccountcontract.include_loss
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setIncludeLoss(Integer includeLoss) {
        this.includeLoss = includeLoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.loss_type
     *
     * @return the value of v_ele_billaccountcontract.loss_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getLossType() {
        return lossType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.loss_type
     *
     * @param lossType the value for v_ele_billaccountcontract.loss_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setLossType(Integer lossType) {
        this.lossType = lossType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.payment_user
     *
     * @return the value of v_ele_billaccountcontract.payment_user
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getPaymentUser() {
        return paymentUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.payment_user
     *
     * @param paymentUser the value for v_ele_billaccountcontract.payment_user
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setPaymentUser(String paymentUser) {
        this.paymentUser = paymentUser == null ? null : paymentUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.payment_telphone
     *
     * @return the value of v_ele_billaccountcontract.payment_telphone
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getPaymentTelphone() {
        return paymentTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.payment_telphone
     *
     * @param paymentTelphone the value for v_ele_billaccountcontract.payment_telphone
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setPaymentTelphone(String paymentTelphone) {
        this.paymentTelphone = paymentTelphone == null ? null : paymentTelphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.elecontract_note
     *
     * @return the value of v_ele_billaccountcontract.elecontract_note
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getElecontractNote() {
        return elecontractNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.elecontract_note
     *
     * @param elecontractNote the value for v_ele_billaccountcontract.elecontract_note
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setElecontractNote(String elecontractNote) {
        this.elecontractNote = elecontractNote == null ? null : elecontractNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.prv_id
     *
     * @return the value of v_ele_billaccountcontract.prv_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getPrvId() {
        return prvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.prv_id
     *
     * @param prvId the value for v_ele_billaccountcontract.prv_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setPrvId(String prvId) {
        this.prvId = prvId == null ? null : prvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.prv_sname
     *
     * @return the value of v_ele_billaccountcontract.prv_sname
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getPrvSname() {
        return prvSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.prv_sname
     *
     * @param prvSname the value for v_ele_billaccountcontract.prv_sname
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setPrvSname(String prvSname) {
        this.prvSname = prvSname == null ? null : prvSname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.preg_id
     *
     * @return the value of v_ele_billaccountcontract.preg_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getPregId() {
        return pregId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.preg_id
     *
     * @param pregId the value for v_ele_billaccountcontract.preg_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setPregId(String pregId) {
        this.pregId = pregId == null ? null : pregId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.preg_name
     *
     * @return the value of v_ele_billaccountcontract.preg_name
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getPregName() {
        return pregName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.preg_name
     *
     * @param pregName the value for v_ele_billaccountcontract.preg_name
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setPregName(String pregName) {
        this.pregName = pregName == null ? null : pregName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.reg_id
     *
     * @return the value of v_ele_billaccountcontract.reg_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.reg_id
     *
     * @param regId the value for v_ele_billaccountcontract.reg_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.reg_name
     *
     * @return the value of v_ele_billaccountcontract.reg_name
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getRegName() {
        return regName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.reg_name
     *
     * @param regName the value for v_ele_billaccountcontract.reg_name
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setRegName(String regName) {
        this.regName = regName == null ? null : regName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.is_downshare
     *
     * @return the value of v_ele_billaccountcontract.is_downshare
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getIsDownshare() {
        return isDownshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.is_downshare
     *
     * @param isDownshare the value for v_ele_billaccountcontract.is_downshare
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setIsDownshare(Integer isDownshare) {
        this.isDownshare = isDownshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.sys_dep_id
     *
     * @return the value of v_ele_billaccountcontract.sys_dep_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getSysDepId() {
        return sysDepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.sys_dep_id
     *
     * @param sysDepId the value for v_ele_billaccountcontract.sys_dep_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setSysDepId(String sysDepId) {
        this.sysDepId = sysDepId == null ? null : sysDepId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.manager_department
     *
     * @return the value of v_ele_billaccountcontract.manager_department
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getManagerDepartment() {
        return managerDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.manager_department
     *
     * @param managerDepartment the value for v_ele_billaccountcontract.manager_department
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setManagerDepartment(String managerDepartment) {
        this.managerDepartment = managerDepartment == null ? null : managerDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.user_id
     *
     * @return the value of v_ele_billaccountcontract.user_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.user_id
     *
     * @param userId the value for v_ele_billaccountcontract.user_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_code
     *
     * @return the value of v_ele_billaccountcontract.contract_code
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_code
     *
     * @param contractCode the value for v_ele_billaccountcontract.contract_code
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode == null ? null : contractCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_name
     *
     * @return the value of v_ele_billaccountcontract.contract_name
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_name
     *
     * @param contractName the value for v_ele_billaccountcontract.contract_name
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_type
     *
     * @return the value of v_ele_billaccountcontract.contract_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getContractType() {
        return contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_type
     *
     * @param contractType the value for v_ele_billaccountcontract.contract_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractType(Integer contractType) {
        this.contractType = contractType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_startdate
     *
     * @return the value of v_ele_billaccountcontract.contract_startdate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    public Date getContractStartdate() {
        return contractStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_startdate
     *
     * @param contractStartdate the value for v_ele_billaccountcontract.contract_startdate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractStartdate(Date contractStartdate) {
        this.contractStartdate = contractStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_enddate
     *
     * @return the value of v_ele_billaccountcontract.contract_enddate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    public Date getContractEnddate() {
        return contractEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_enddate
     *
     * @param contractEnddate the value for v_ele_billaccountcontract.contract_enddate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractEnddate(Date contractEnddate) {
        this.contractEnddate = contractEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_signdate
     *
     * @return the value of v_ele_billaccountcontract.contract_signdate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    public Date getContractSigndate() {
        return contractSigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_signdate
     *
     * @param contractSigndate the value for v_ele_billaccountcontract.contract_signdate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractSigndate(Date contractSigndate) {
        this.contractSigndate = contractSigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_yearquantity
     *
     * @return the value of v_ele_billaccountcontract.contract_yearquantity
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public BigDecimal getContractYearquantity() {
        return contractYearquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_yearquantity
     *
     * @param contractYearquantity the value for v_ele_billaccountcontract.contract_yearquantity
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractYearquantity(BigDecimal contractYearquantity) {
        this.contractYearquantity = contractYearquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_checkname1
     *
     * @return the value of v_ele_billaccountcontract.contract_checkname1
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getContractCheckname1() {
        return contractCheckname1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_checkname1
     *
     * @param contractCheckname1 the value for v_ele_billaccountcontract.contract_checkname1
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractCheckname1(String contractCheckname1) {
        this.contractCheckname1 = contractCheckname1 == null ? null : contractCheckname1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_checkname2
     *
     * @return the value of v_ele_billaccountcontract.contract_checkname2
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getContractCheckname2() {
        return contractCheckname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_checkname2
     *
     * @param contractCheckname2 the value for v_ele_billaccountcontract.contract_checkname2
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractCheckname2(String contractCheckname2) {
        this.contractCheckname2 = contractCheckname2 == null ? null : contractCheckname2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.old_contract_id
     *
     * @return the value of v_ele_billaccountcontract.old_contract_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getOldContractId() {
        return oldContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.old_contract_id
     *
     * @param oldContractId the value for v_ele_billaccountcontract.old_contract_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setOldContractId(String oldContractId) {
        this.oldContractId = oldContractId == null ? null : oldContractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.old_contract_code
     *
     * @return the value of v_ele_billaccountcontract.old_contract_code
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getOldContractCode() {
        return oldContractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.old_contract_code
     *
     * @param oldContractCode the value for v_ele_billaccountcontract.old_contract_code
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setOldContractCode(String oldContractCode) {
        this.oldContractCode = oldContractCode == null ? null : oldContractCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_flow
     *
     * @return the value of v_ele_billaccountcontract.contract_flow
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getContractFlow() {
        return contractFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_flow
     *
     * @param contractFlow the value for v_ele_billaccountcontract.contract_flow
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractFlow(String contractFlow) {
        this.contractFlow = contractFlow == null ? null : contractFlow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_introduction
     *
     * @return the value of v_ele_billaccountcontract.contract_introduction
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getContractIntroduction() {
        return contractIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_introduction
     *
     * @param contractIntroduction the value for v_ele_billaccountcontract.contract_introduction
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractIntroduction(String contractIntroduction) {
        this.contractIntroduction = contractIntroduction == null ? null : contractIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_spaceresource
     *
     * @return the value of v_ele_billaccountcontract.contract_spaceresource
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getContractSpaceresource() {
        return contractSpaceresource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_spaceresource
     *
     * @param contractSpaceresource the value for v_ele_billaccountcontract.contract_spaceresource
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractSpaceresource(String contractSpaceresource) {
        this.contractSpaceresource = contractSpaceresource == null ? null : contractSpaceresource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_state
     *
     * @return the value of v_ele_billaccountcontract.contract_state
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getContractState() {
        return contractState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_state
     *
     * @param contractState the value for v_ele_billaccountcontract.contract_state
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractState(Integer contractState) {
        this.contractState = contractState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.contract_note
     *
     * @return the value of v_ele_billaccountcontract.contract_note
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getContractNote() {
        return contractNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.contract_note
     *
     * @param contractNote the value for v_ele_billaccountcontract.contract_note
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setContractNote(String contractNote) {
        this.contractNote = contractNote == null ? null : contractNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.auditing_state
     *
     * @return the value of v_ele_billaccountcontract.auditing_state
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getAuditingState() {
        return auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.auditing_state
     *
     * @param auditingState the value for v_ele_billaccountcontract.auditing_state
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setAuditingState(Integer auditingState) {
        this.auditingState = auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.auditing_user_id
     *
     * @return the value of v_ele_billaccountcontract.auditing_user_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getAuditingUserId() {
        return auditingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.auditing_user_id
     *
     * @param auditingUserId the value for v_ele_billaccountcontract.auditing_user_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setAuditingUserId(String auditingUserId) {
        this.auditingUserId = auditingUserId == null ? null : auditingUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.auditing_date
     *
     * @return the value of v_ele_billaccountcontract.auditing_date
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    public Date getAuditingDate() {
        return auditingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.auditing_date
     *
     * @param auditingDate the value for v_ele_billaccountcontract.auditing_date
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setAuditingDate(Date auditingDate) {
        this.auditingDate = auditingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.data_from
     *
     * @return the value of v_ele_billaccountcontract.data_from
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.data_from
     *
     * @param dataFrom the value for v_ele_billaccountcontract.data_from
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setDataFrom(Integer dataFrom) {
        this.dataFrom = dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.supplier_code
     *
     * @return the value of v_ele_billaccountcontract.supplier_code
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.supplier_code
     *
     * @param supplierCode the value for v_ele_billaccountcontract.supplier_code
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.supplier_name
     *
     * @return the value of v_ele_billaccountcontract.supplier_name
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.supplier_name
     *
     * @param supplierName the value for v_ele_billaccountcontract.supplier_name
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.supplier_address
     *
     * @return the value of v_ele_billaccountcontract.supplier_address
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getSupplierAddress() {
        return supplierAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.supplier_address
     *
     * @param supplierAddress the value for v_ele_billaccountcontract.supplier_address
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress == null ? null : supplierAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.supplier_contact
     *
     * @return the value of v_ele_billaccountcontract.supplier_contact
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getSupplierContact() {
        return supplierContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.supplier_contact
     *
     * @param supplierContact the value for v_ele_billaccountcontract.supplier_contact
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setSupplierContact(String supplierContact) {
        this.supplierContact = supplierContact == null ? null : supplierContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.supplier_telephone
     *
     * @return the value of v_ele_billaccountcontract.supplier_telephone
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getSupplierTelephone() {
        return supplierTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.supplier_telephone
     *
     * @param supplierTelephone the value for v_ele_billaccountcontract.supplier_telephone
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setSupplierTelephone(String supplierTelephone) {
        this.supplierTelephone = supplierTelephone == null ? null : supplierTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.supplier_type
     *
     * @return the value of v_ele_billaccountcontract.supplier_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getSupplierType() {
        return supplierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.supplier_type
     *
     * @param supplierType the value for v_ele_billaccountcontract.supplier_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setSupplierType(Integer supplierType) {
        this.supplierType = supplierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.account_type
     *
     * @return the value of v_ele_billaccountcontract.account_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.account_type
     *
     * @param accountType the value for v_ele_billaccountcontract.account_type
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.bank_user
     *
     * @return the value of v_ele_billaccountcontract.bank_user
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getBankUser() {
        return bankUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.bank_user
     *
     * @param bankUser the value for v_ele_billaccountcontract.bank_user
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setBankUser(String bankUser) {
        this.bankUser = bankUser == null ? null : bankUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.deposit_bank
     *
     * @return the value of v_ele_billaccountcontract.deposit_bank
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getDepositBank() {
        return depositBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.deposit_bank
     *
     * @param depositBank the value for v_ele_billaccountcontract.deposit_bank
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setDepositBank(String depositBank) {
        this.depositBank = depositBank == null ? null : depositBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.bank_account
     *
     * @return the value of v_ele_billaccountcontract.bank_account
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.bank_account
     *
     * @param bankAccount the value for v_ele_billaccountcontract.bank_account
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.supplier_state
     *
     * @return the value of v_ele_billaccountcontract.supplier_state
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getSupplierState() {
        return supplierState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.supplier_state
     *
     * @param supplierState the value for v_ele_billaccountcontract.supplier_state
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setSupplierState(Integer supplierState) {
        this.supplierState = supplierState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.supplier_note
     *
     * @return the value of v_ele_billaccountcontract.supplier_note
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getSupplierNote() {
        return supplierNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.supplier_note
     *
     * @param supplierNote the value for v_ele_billaccountcontract.supplier_note
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setSupplierNote(String supplierNote) {
        this.supplierNote = supplierNote == null ? null : supplierNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.elebillaccountcontract_id
     *
     * @return the value of v_ele_billaccountcontract.elebillaccountcontract_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getElebillaccountcontractId() {
        return elebillaccountcontractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.elebillaccountcontract_id
     *
     * @param elebillaccountcontractId the value for v_ele_billaccountcontract.elebillaccountcontract_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setElebillaccountcontractId(String elebillaccountcontractId) {
        this.elebillaccountcontractId = elebillaccountcontractId == null ? null : elebillaccountcontractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.billaccount_id
     *
     * @return the value of v_ele_billaccountcontract.billaccount_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public String getBillaccountId() {
        return billaccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.billaccount_id
     *
     * @param billaccountId the value for v_ele_billaccountcontract.billaccount_id
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setBillaccountId(String billaccountId) {
        this.billaccountId = billaccountId == null ? null : billaccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.relation_state
     *
     * @return the value of v_ele_billaccountcontract.relation_state
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public Integer getRelationState() {
        return relationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.relation_state
     *
     * @param relationState the value for v_ele_billaccountcontract.relation_state
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setRelationState(Integer relationState) {
        this.relationState = relationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.relation_startdate
     *
     * @return the value of v_ele_billaccountcontract.relation_startdate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    public Date getRelationStartdate() {
        return relationStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.relation_startdate
     *
     * @param relationStartdate the value for v_ele_billaccountcontract.relation_startdate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setRelationStartdate(Date relationStartdate) {
        this.relationStartdate = relationStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccountcontract.relation_enddate
     *
     * @return the value of v_ele_billaccountcontract.relation_enddate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    public Date getRelationEnddate() {
        return relationEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccountcontract.relation_enddate
     *
     * @param relationEnddate the value for v_ele_billaccountcontract.relation_enddate
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    public void setRelationEnddate(Date relationEnddate) {
        this.relationEnddate = relationEnddate;
    }
}