package com.xunge.model.selfelec;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import cn.afterturn.easypoi.excel.annotation.Excel;

import com.fasterxml.jackson.annotation.JsonFormat;

public class VEleBillamountPayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billaccountpaymentdetail_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String billaccountpaymentdetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billamount_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String billamountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billaccount_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String billaccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billamount_startdate
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @Excel(name="缴费期始",orderNum="15",format="yyyy-MM-dd",databaseFormat="yyyy-MM-dd")
    private Date billamountStartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billamount_enddate
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @Excel(name="缴费期终",orderNum="20",format="yyyy-MM-dd",databaseFormat="yyyy-MM-dd")
    private Date billamountEnddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billamount_date
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @Excel(name="缴费日期",orderNum="30",format="yyyy-MM-dd",databaseFormat="yyyy-MM-dd")
    private Date billamountDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.buy_method
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private Integer buyMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.payment_method
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private Integer paymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.bill_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private Integer billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.invoice_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private Integer invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.tax_payment_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private Integer taxPaymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.is_vat_deduction
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private Integer isVatDeduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.business_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private Integer businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.amount_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private Integer amountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billamount_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private Integer billamountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billamount_notax_sys
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private BigDecimal billamountNotaxSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billamount_notax
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @Excel(name="不含税金额",orderNum="3")
    private BigDecimal billamountNotax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.loss_amount_sys
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private BigDecimal lossAmountSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.loss_amount
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private BigDecimal lossAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billamount_taxamount_sys
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private BigDecimal billamountTaxamountSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billamount_taxamount
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @Excel(name="税金",orderNum="5")
    private BigDecimal billamountTaxamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.other_amount
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private BigDecimal otherAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.bill_amount_sys
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private BigDecimal billAmountSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.bill_amount_actual
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @Excel(name="实际报账金额",orderNum="10")
    private BigDecimal billAmountActual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.total_degree
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private BigDecimal totalDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.calc_multi
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private BigDecimal calcMulti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.total_degree_actual
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @Excel(name="用电度数",orderNum="8")
    private BigDecimal totalDegreeActual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.paymentdetail_note
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String paymentdetailNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.submit_state
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private Integer submitState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.auditing_state
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private Integer auditingState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.auditing_user_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String auditingUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.auditing_date
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private Date auditingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.prv_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String prvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.prv_sname
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String prvSname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.preg_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String pregName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.reg_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String regName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.preg_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String pregId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.reg_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billaccount_code
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String billaccountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billaccount_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @Excel(name="报账点名称",orderNum="2")
    private String billaccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.elecontract_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String elecontractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.contract_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.contract_code
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @Excel(name="合同编号",orderNum="1")
    private String contractCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.contract_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.supplier_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.supplier_code
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.supplier_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.supplier_address
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String supplierAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.supplier_contact
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String supplierContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.supplier_telephone
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String supplierTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.bank_user
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String bankUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.deposit_bank
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String depositBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.bank_account
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.tax_rate
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @Excel(name="税率（%）",orderNum="4")
    private BigDecimal taxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.detail_cnt
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @Excel(name="电表缴费数量",orderNum="6")
    private Long detailCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.billamount_price
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private BigDecimal billamountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.payment_user
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    
    private String paymentUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.payment_usertel
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
   
    private String paymentUsertel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.operator
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billamount_payment.operate_tel
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    private String operateTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billaccountpaymentdetail_id
     *
     * @return the value of v_ele_billamount_payment.billaccountpaymentdetail_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getBillaccountpaymentdetailId() {
        return billaccountpaymentdetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billaccountpaymentdetail_id
     *
     * @param billaccountpaymentdetailId the value for v_ele_billamount_payment.billaccountpaymentdetail_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillaccountpaymentdetailId(String billaccountpaymentdetailId) {
        this.billaccountpaymentdetailId = billaccountpaymentdetailId == null ? null : billaccountpaymentdetailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billamount_id
     *
     * @return the value of v_ele_billamount_payment.billamount_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getBillamountId() {
        return billamountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billamount_id
     *
     * @param billamountId the value for v_ele_billamount_payment.billamount_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillamountId(String billamountId) {
        this.billamountId = billamountId == null ? null : billamountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billaccount_id
     *
     * @return the value of v_ele_billamount_payment.billaccount_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getBillaccountId() {
        return billaccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billaccount_id
     *
     * @param billaccountId the value for v_ele_billamount_payment.billaccount_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillaccountId(String billaccountId) {
        this.billaccountId = billaccountId == null ? null : billaccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billamount_startdate
     *
     * @return the value of v_ele_billamount_payment.billamount_startdate
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getBillamountStartdate() {
        return billamountStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billamount_startdate
     *
     * @param billamountStartdate the value for v_ele_billamount_payment.billamount_startdate
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillamountStartdate(Date billamountStartdate) {
        this.billamountStartdate = billamountStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billamount_enddate
     *
     * @return the value of v_ele_billamount_payment.billamount_enddate
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getBillamountEnddate() {
        return billamountEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billamount_enddate
     *
     * @param billamountEnddate the value for v_ele_billamount_payment.billamount_enddate
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillamountEnddate(Date billamountEnddate) {
        this.billamountEnddate = billamountEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billamount_date
     *
     * @return the value of v_ele_billamount_payment.billamount_date
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getBillamountDate() {
        return billamountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billamount_date
     *
     * @param billamountDate the value for v_ele_billamount_payment.billamount_date
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillamountDate(Date billamountDate) {
        this.billamountDate = billamountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.buy_method
     *
     * @return the value of v_ele_billamount_payment.buy_method
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public Integer getBuyMethod() {
        return buyMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.buy_method
     *
     * @param buyMethod the value for v_ele_billamount_payment.buy_method
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBuyMethod(Integer buyMethod) {
        this.buyMethod = buyMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.payment_method
     *
     * @return the value of v_ele_billamount_payment.payment_method
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public Integer getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.payment_method
     *
     * @param paymentMethod the value for v_ele_billamount_payment.payment_method
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setPaymentMethod(Integer paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.bill_type
     *
     * @return the value of v_ele_billamount_payment.bill_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public Integer getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.bill_type
     *
     * @param billType the value for v_ele_billamount_payment.bill_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillType(Integer billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.invoice_type
     *
     * @return the value of v_ele_billamount_payment.invoice_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public Integer getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.invoice_type
     *
     * @param invoiceType the value for v_ele_billamount_payment.invoice_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setInvoiceType(Integer invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.tax_payment_type
     *
     * @return the value of v_ele_billamount_payment.tax_payment_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public Integer getTaxPaymentType() {
        return taxPaymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.tax_payment_type
     *
     * @param taxPaymentType the value for v_ele_billamount_payment.tax_payment_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setTaxPaymentType(Integer taxPaymentType) {
        this.taxPaymentType = taxPaymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.is_vat_deduction
     *
     * @return the value of v_ele_billamount_payment.is_vat_deduction
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public Integer getIsVatDeduction() {
        return isVatDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.is_vat_deduction
     *
     * @param isVatDeduction the value for v_ele_billamount_payment.is_vat_deduction
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setIsVatDeduction(Integer isVatDeduction) {
        this.isVatDeduction = isVatDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.business_type
     *
     * @return the value of v_ele_billamount_payment.business_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.business_type
     *
     * @param businessType the value for v_ele_billamount_payment.business_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.amount_type
     *
     * @return the value of v_ele_billamount_payment.amount_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public Integer getAmountType() {
        return amountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.amount_type
     *
     * @param amountType the value for v_ele_billamount_payment.amount_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setAmountType(Integer amountType) {
        this.amountType = amountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billamount_type
     *
     * @return the value of v_ele_billamount_payment.billamount_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public Integer getBillamountType() {
        return billamountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billamount_type
     *
     * @param billamountType the value for v_ele_billamount_payment.billamount_type
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillamountType(Integer billamountType) {
        this.billamountType = billamountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billamount_notax_sys
     *
     * @return the value of v_ele_billamount_payment.billamount_notax_sys
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getBillamountNotaxSys() {
        return billamountNotaxSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billamount_notax_sys
     *
     * @param billamountNotaxSys the value for v_ele_billamount_payment.billamount_notax_sys
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillamountNotaxSys(BigDecimal billamountNotaxSys) {
        this.billamountNotaxSys = billamountNotaxSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billamount_notax
     *
     * @return the value of v_ele_billamount_payment.billamount_notax
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getBillamountNotax() {
        return billamountNotax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billamount_notax
     *
     * @param billamountNotax the value for v_ele_billamount_payment.billamount_notax
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillamountNotax(BigDecimal billamountNotax) {
        this.billamountNotax = billamountNotax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.loss_amount_sys
     *
     * @return the value of v_ele_billamount_payment.loss_amount_sys
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getLossAmountSys() {
        return lossAmountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.loss_amount_sys
     *
     * @param lossAmountSys the value for v_ele_billamount_payment.loss_amount_sys
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setLossAmountSys(BigDecimal lossAmountSys) {
        this.lossAmountSys = lossAmountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.loss_amount
     *
     * @return the value of v_ele_billamount_payment.loss_amount
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getLossAmount() {
        return lossAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.loss_amount
     *
     * @param lossAmount the value for v_ele_billamount_payment.loss_amount
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setLossAmount(BigDecimal lossAmount) {
        this.lossAmount = lossAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billamount_taxamount_sys
     *
     * @return the value of v_ele_billamount_payment.billamount_taxamount_sys
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getBillamountTaxamountSys() {
        return billamountTaxamountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billamount_taxamount_sys
     *
     * @param billamountTaxamountSys the value for v_ele_billamount_payment.billamount_taxamount_sys
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillamountTaxamountSys(BigDecimal billamountTaxamountSys) {
        this.billamountTaxamountSys = billamountTaxamountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billamount_taxamount
     *
     * @return the value of v_ele_billamount_payment.billamount_taxamount
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getBillamountTaxamount() {
        return billamountTaxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billamount_taxamount
     *
     * @param billamountTaxamount the value for v_ele_billamount_payment.billamount_taxamount
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillamountTaxamount(BigDecimal billamountTaxamount) {
        this.billamountTaxamount = billamountTaxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.other_amount
     *
     * @return the value of v_ele_billamount_payment.other_amount
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getOtherAmount() {
        return otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.other_amount
     *
     * @param otherAmount the value for v_ele_billamount_payment.other_amount
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setOtherAmount(BigDecimal otherAmount) {
        this.otherAmount = otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.bill_amount_sys
     *
     * @return the value of v_ele_billamount_payment.bill_amount_sys
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getBillAmountSys() {
        return billAmountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.bill_amount_sys
     *
     * @param billAmountSys the value for v_ele_billamount_payment.bill_amount_sys
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillAmountSys(BigDecimal billAmountSys) {
        this.billAmountSys = billAmountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.bill_amount_actual
     *
     * @return the value of v_ele_billamount_payment.bill_amount_actual
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getBillAmountActual() {
        return billAmountActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.bill_amount_actual
     *
     * @param billAmountActual the value for v_ele_billamount_payment.bill_amount_actual
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillAmountActual(BigDecimal billAmountActual) {
        this.billAmountActual = billAmountActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.total_degree
     *
     * @return the value of v_ele_billamount_payment.total_degree
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getTotalDegree() {
        return totalDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.total_degree
     *
     * @param totalDegree the value for v_ele_billamount_payment.total_degree
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setTotalDegree(BigDecimal totalDegree) {
        this.totalDegree = totalDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.calc_multi
     *
     * @return the value of v_ele_billamount_payment.calc_multi
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getCalcMulti() {
        return calcMulti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.calc_multi
     *
     * @param calcMulti the value for v_ele_billamount_payment.calc_multi
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setCalcMulti(BigDecimal calcMulti) {
        this.calcMulti = calcMulti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.total_degree_actual
     *
     * @return the value of v_ele_billamount_payment.total_degree_actual
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getTotalDegreeActual() {
        return totalDegreeActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.total_degree_actual
     *
     * @param totalDegreeActual the value for v_ele_billamount_payment.total_degree_actual
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setTotalDegreeActual(BigDecimal totalDegreeActual) {
        this.totalDegreeActual = totalDegreeActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.paymentdetail_note
     *
     * @return the value of v_ele_billamount_payment.paymentdetail_note
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getPaymentdetailNote() {
        return paymentdetailNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.paymentdetail_note
     *
     * @param paymentdetailNote the value for v_ele_billamount_payment.paymentdetail_note
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setPaymentdetailNote(String paymentdetailNote) {
        this.paymentdetailNote = paymentdetailNote == null ? null : paymentdetailNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.submit_state
     *
     * @return the value of v_ele_billamount_payment.submit_state
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public Integer getSubmitState() {
        return submitState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.submit_state
     *
     * @param submitState the value for v_ele_billamount_payment.submit_state
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setSubmitState(Integer submitState) {
        this.submitState = submitState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.auditing_state
     *
     * @return the value of v_ele_billamount_payment.auditing_state
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public Integer getAuditingState() {
        return auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.auditing_state
     *
     * @param auditingState the value for v_ele_billamount_payment.auditing_state
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setAuditingState(Integer auditingState) {
        this.auditingState = auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.auditing_user_id
     *
     * @return the value of v_ele_billamount_payment.auditing_user_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getAuditingUserId() {
        return auditingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.auditing_user_id
     *
     * @param auditingUserId the value for v_ele_billamount_payment.auditing_user_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setAuditingUserId(String auditingUserId) {
        this.auditingUserId = auditingUserId == null ? null : auditingUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.auditing_date
     *
     * @return the value of v_ele_billamount_payment.auditing_date
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getAuditingDate() {
        return auditingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.auditing_date
     *
     * @param auditingDate the value for v_ele_billamount_payment.auditing_date
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setAuditingDate(Date auditingDate) {
        this.auditingDate = auditingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.prv_id
     *
     * @return the value of v_ele_billamount_payment.prv_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getPrvId() {
        return prvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.prv_id
     *
     * @param prvId the value for v_ele_billamount_payment.prv_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setPrvId(String prvId) {
        this.prvId = prvId == null ? null : prvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.prv_sname
     *
     * @return the value of v_ele_billamount_payment.prv_sname
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getPrvSname() {
        return prvSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.prv_sname
     *
     * @param prvSname the value for v_ele_billamount_payment.prv_sname
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setPrvSname(String prvSname) {
        this.prvSname = prvSname == null ? null : prvSname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.preg_name
     *
     * @return the value of v_ele_billamount_payment.preg_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getPregName() {
        return pregName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.preg_name
     *
     * @param pregName the value for v_ele_billamount_payment.preg_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setPregName(String pregName) {
        this.pregName = pregName == null ? null : pregName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.reg_name
     *
     * @return the value of v_ele_billamount_payment.reg_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getRegName() {
        return regName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.reg_name
     *
     * @param regName the value for v_ele_billamount_payment.reg_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setRegName(String regName) {
        this.regName = regName == null ? null : regName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.preg_id
     *
     * @return the value of v_ele_billamount_payment.preg_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getPregId() {
        return pregId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.preg_id
     *
     * @param pregId the value for v_ele_billamount_payment.preg_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setPregId(String pregId) {
        this.pregId = pregId == null ? null : pregId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.reg_id
     *
     * @return the value of v_ele_billamount_payment.reg_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.reg_id
     *
     * @param regId the value for v_ele_billamount_payment.reg_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billaccount_code
     *
     * @return the value of v_ele_billamount_payment.billaccount_code
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getBillaccountCode() {
        return billaccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billaccount_code
     *
     * @param billaccountCode the value for v_ele_billamount_payment.billaccount_code
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillaccountCode(String billaccountCode) {
        this.billaccountCode = billaccountCode == null ? null : billaccountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billaccount_name
     *
     * @return the value of v_ele_billamount_payment.billaccount_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getBillaccountName() {
        return billaccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billaccount_name
     *
     * @param billaccountName the value for v_ele_billamount_payment.billaccount_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillaccountName(String billaccountName) {
        this.billaccountName = billaccountName == null ? null : billaccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.elecontract_id
     *
     * @return the value of v_ele_billamount_payment.elecontract_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getElecontractId() {
        return elecontractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.elecontract_id
     *
     * @param elecontractId the value for v_ele_billamount_payment.elecontract_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setElecontractId(String elecontractId) {
        this.elecontractId = elecontractId == null ? null : elecontractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.contract_id
     *
     * @return the value of v_ele_billamount_payment.contract_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.contract_id
     *
     * @param contractId the value for v_ele_billamount_payment.contract_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setContractId(String contractId) {
        this.contractId = contractId == null ? null : contractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.contract_code
     *
     * @return the value of v_ele_billamount_payment.contract_code
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.contract_code
     *
     * @param contractCode the value for v_ele_billamount_payment.contract_code
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode == null ? null : contractCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.contract_name
     *
     * @return the value of v_ele_billamount_payment.contract_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.contract_name
     *
     * @param contractName the value for v_ele_billamount_payment.contract_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.supplier_id
     *
     * @return the value of v_ele_billamount_payment.supplier_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.supplier_id
     *
     * @param supplierId the value for v_ele_billamount_payment.supplier_id
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId == null ? null : supplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.supplier_code
     *
     * @return the value of v_ele_billamount_payment.supplier_code
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.supplier_code
     *
     * @param supplierCode the value for v_ele_billamount_payment.supplier_code
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.supplier_name
     *
     * @return the value of v_ele_billamount_payment.supplier_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.supplier_name
     *
     * @param supplierName the value for v_ele_billamount_payment.supplier_name
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.supplier_address
     *
     * @return the value of v_ele_billamount_payment.supplier_address
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getSupplierAddress() {
        return supplierAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.supplier_address
     *
     * @param supplierAddress the value for v_ele_billamount_payment.supplier_address
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress == null ? null : supplierAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.supplier_contact
     *
     * @return the value of v_ele_billamount_payment.supplier_contact
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getSupplierContact() {
        return supplierContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.supplier_contact
     *
     * @param supplierContact the value for v_ele_billamount_payment.supplier_contact
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setSupplierContact(String supplierContact) {
        this.supplierContact = supplierContact == null ? null : supplierContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.supplier_telephone
     *
     * @return the value of v_ele_billamount_payment.supplier_telephone
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getSupplierTelephone() {
        return supplierTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.supplier_telephone
     *
     * @param supplierTelephone the value for v_ele_billamount_payment.supplier_telephone
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setSupplierTelephone(String supplierTelephone) {
        this.supplierTelephone = supplierTelephone == null ? null : supplierTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.bank_user
     *
     * @return the value of v_ele_billamount_payment.bank_user
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getBankUser() {
        return bankUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.bank_user
     *
     * @param bankUser the value for v_ele_billamount_payment.bank_user
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBankUser(String bankUser) {
        this.bankUser = bankUser == null ? null : bankUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.deposit_bank
     *
     * @return the value of v_ele_billamount_payment.deposit_bank
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getDepositBank() {
        return depositBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.deposit_bank
     *
     * @param depositBank the value for v_ele_billamount_payment.deposit_bank
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setDepositBank(String depositBank) {
        this.depositBank = depositBank == null ? null : depositBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.bank_account
     *
     * @return the value of v_ele_billamount_payment.bank_account
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.bank_account
     *
     * @param bankAccount the value for v_ele_billamount_payment.bank_account
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.tax_rate
     *
     * @return the value of v_ele_billamount_payment.tax_rate
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.tax_rate
     *
     * @param taxRate the value for v_ele_billamount_payment.tax_rate
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setTaxRate(BigDecimal taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.detail_cnt
     *
     * @return the value of v_ele_billamount_payment.detail_cnt
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public Long getDetailCnt() {
        return detailCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.detail_cnt
     *
     * @param detailCnt the value for v_ele_billamount_payment.detail_cnt
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setDetailCnt(Long detailCnt) {
        this.detailCnt = detailCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.billamount_price
     *
     * @return the value of v_ele_billamount_payment.billamount_price
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public BigDecimal getBillamountPrice() {
        return billamountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.billamount_price
     *
     * @param billamountPrice the value for v_ele_billamount_payment.billamount_price
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setBillamountPrice(BigDecimal billamountPrice) {
        this.billamountPrice = billamountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.payment_user
     *
     * @return the value of v_ele_billamount_payment.payment_user
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getPaymentUser() {
        return paymentUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.payment_user
     *
     * @param paymentUser the value for v_ele_billamount_payment.payment_user
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setPaymentUser(String paymentUser) {
        this.paymentUser = paymentUser == null ? null : paymentUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.payment_usertel
     *
     * @return the value of v_ele_billamount_payment.payment_usertel
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getPaymentUsertel() {
        return paymentUsertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.payment_usertel
     *
     * @param paymentUsertel the value for v_ele_billamount_payment.payment_usertel
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setPaymentUsertel(String paymentUsertel) {
        this.paymentUsertel = paymentUsertel == null ? null : paymentUsertel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.operator
     *
     * @return the value of v_ele_billamount_payment.operator
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.operator
     *
     * @param operator the value for v_ele_billamount_payment.operator
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billamount_payment.operate_tel
     *
     * @return the value of v_ele_billamount_payment.operate_tel
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public String getOperateTel() {
        return operateTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billamount_payment.operate_tel
     *
     * @param operateTel the value for v_ele_billamount_payment.operate_tel
     *
     * @mbggenerated Sat Aug 12 00:33:43 CST 2017
     */
    public void setOperateTel(String operateTel) {
        this.operateTel = operateTel == null ? null : operateTel.trim();
    }
}