package com.xunge.model.selfelec;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import cn.afterturn.easypoi.excel.annotation.Excel;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.xunge.model.activity.Act;

public class VEleBillaccountPaymentInfo {
	
	//计划缴费日期
	@Excel(name="计划缴费日期",orderNum="14",format="yyyy-MM-dd")
	private Date planDate;
	
    public Date getPlanDate() {
		return planDate;
	}

	public void setPlanDate(Date planDate) {
		this.planDate = planDate;
	}
	@Excel(name="报账点状态",replace={"正常_0","暂停_9","已删除_-1"},orderNum="10")
	private Integer billaccountState;
	
	private Integer paymentState;
	
	
    public Integer getBillaccountState() {
		return billaccountState;
	}

	public void setBillaccountState(Integer billaccountState) {
		this.billaccountState = billaccountState;
	}

	public Integer getPaymentState() {
		return paymentState;
	}

	public void setPaymentState(Integer paymentState) {
		this.paymentState = paymentState;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.billaccountpaymentdetail_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private String billaccountpaymentdetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.billaccount_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private String billaccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.billamount_startdate
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Date billamountStartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.billamount_enddate
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    @Excel(name="上次缴费期终",orderNum="12",format="yyyy-MM-dd")
    private Date billamountEnddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.billamount_date
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Date billamountDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.buy_method
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Integer buyMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.payment_method
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Integer paymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.bill_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Integer billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.invoice_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Integer invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.tax_payment_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Integer taxPaymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.is_vat_deduction
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Integer isVatDeduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.business_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Integer businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.amount_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Integer amountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.billamount_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Integer billamountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.billamount_notax_sys
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal billamountNotaxSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.billamount_notax
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal billamountNotax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.loss_amount_sys
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal lossAmountSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.loss_amount
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal lossAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.billamount_taxamount_sys
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal billamountTaxamountSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.billamount_taxamount
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal billamountTaxamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.other_amount
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal otherAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.bill_amount_sys
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal billAmountSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.bill_amount_actual
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal billAmountActual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.total_degree
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal totalDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.calc_multi
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal calcMulti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.total_degree_actual
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal totalDegreeActual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.submit_state
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Integer submitState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.auditing_state
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Integer auditingState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.auditing_user_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private String auditingUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.auditing_date
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private Date auditingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.paymentdetail_note
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private String paymentdetailNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.preg_name
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    @Excel(name="所属地市",orderNum="4")
    private String pregName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.reg_name
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
   	@Excel(name="所属区县",orderNum="6")
    private String regName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.preg_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private String pregId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.reg_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.billaccount_code
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    @Excel(name="报账点编码",orderNum="0")
    private String billaccountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.billaccount_name
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    @Excel(name="报账点名称",orderNum="2")
    private String billaccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.contract_code
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private String contractCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.contract_name
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private String contractName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_ele_billaccount_payment_info.tax_rate
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    private BigDecimal taxRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.billaccountpaymentdetail_id
     *
     * @return the value of v_ele_billaccount_payment_info.billaccountpaymentdetail_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public String getBillaccountpaymentdetailId() {
        return billaccountpaymentdetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.billaccountpaymentdetail_id
     *
     * @param billaccountpaymentdetailId the value for v_ele_billaccount_payment_info.billaccountpaymentdetail_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillaccountpaymentdetailId(String billaccountpaymentdetailId) {
        this.billaccountpaymentdetailId = billaccountpaymentdetailId == null ? null : billaccountpaymentdetailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.billaccount_id
     *
     * @return the value of v_ele_billaccount_payment_info.billaccount_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public String getBillaccountId() {
        return billaccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.billaccount_id
     *
     * @param billaccountId the value for v_ele_billaccount_payment_info.billaccount_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillaccountId(String billaccountId) {
        this.billaccountId = billaccountId == null ? null : billaccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.billamount_startdate
     *
     * @return the value of v_ele_billaccount_payment_info.billamount_startdate
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getBillamountStartdate() {
        return billamountStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.billamount_startdate
     *
     * @param billamountStartdate the value for v_ele_billaccount_payment_info.billamount_startdate
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillamountStartdate(Date billamountStartdate) {
        this.billamountStartdate = billamountStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.billamount_enddate
     *
     * @return the value of v_ele_billaccount_payment_info.billamount_enddate
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getBillamountEnddate() {
        return billamountEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.billamount_enddate
     *
     * @param billamountEnddate the value for v_ele_billaccount_payment_info.billamount_enddate
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillamountEnddate(Date billamountEnddate) {
        this.billamountEnddate = billamountEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.billamount_date
     *
     * @return the value of v_ele_billaccount_payment_info.billamount_date
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getBillamountDate() {
        return billamountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.billamount_date
     *
     * @param billamountDate the value for v_ele_billaccount_payment_info.billamount_date
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillamountDate(Date billamountDate) {
        this.billamountDate = billamountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.buy_method
     *
     * @return the value of v_ele_billaccount_payment_info.buy_method
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public Integer getBuyMethod() {
        return buyMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.buy_method
     *
     * @param buyMethod the value for v_ele_billaccount_payment_info.buy_method
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBuyMethod(Integer buyMethod) {
        this.buyMethod = buyMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.payment_method
     *
     * @return the value of v_ele_billaccount_payment_info.payment_method
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public Integer getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.payment_method
     *
     * @param paymentMethod the value for v_ele_billaccount_payment_info.payment_method
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setPaymentMethod(Integer paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.bill_type
     *
     * @return the value of v_ele_billaccount_payment_info.bill_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public Integer getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.bill_type
     *
     * @param billType the value for v_ele_billaccount_payment_info.bill_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillType(Integer billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.invoice_type
     *
     * @return the value of v_ele_billaccount_payment_info.invoice_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public Integer getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.invoice_type
     *
     * @param invoiceType the value for v_ele_billaccount_payment_info.invoice_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setInvoiceType(Integer invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.tax_payment_type
     *
     * @return the value of v_ele_billaccount_payment_info.tax_payment_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public Integer getTaxPaymentType() {
        return taxPaymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.tax_payment_type
     *
     * @param taxPaymentType the value for v_ele_billaccount_payment_info.tax_payment_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setTaxPaymentType(Integer taxPaymentType) {
        this.taxPaymentType = taxPaymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.is_vat_deduction
     *
     * @return the value of v_ele_billaccount_payment_info.is_vat_deduction
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public Integer getIsVatDeduction() {
        return isVatDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.is_vat_deduction
     *
     * @param isVatDeduction the value for v_ele_billaccount_payment_info.is_vat_deduction
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setIsVatDeduction(Integer isVatDeduction) {
        this.isVatDeduction = isVatDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.business_type
     *
     * @return the value of v_ele_billaccount_payment_info.business_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.business_type
     *
     * @param businessType the value for v_ele_billaccount_payment_info.business_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.amount_type
     *
     * @return the value of v_ele_billaccount_payment_info.amount_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public Integer getAmountType() {
        return amountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.amount_type
     *
     * @param amountType the value for v_ele_billaccount_payment_info.amount_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setAmountType(Integer amountType) {
        this.amountType = amountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.billamount_type
     *
     * @return the value of v_ele_billaccount_payment_info.billamount_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public Integer getBillamountType() {
        return billamountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.billamount_type
     *
     * @param billamountType the value for v_ele_billaccount_payment_info.billamount_type
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillamountType(Integer billamountType) {
        this.billamountType = billamountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.billamount_notax_sys
     *
     * @return the value of v_ele_billaccount_payment_info.billamount_notax_sys
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getBillamountNotaxSys() {
        return billamountNotaxSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.billamount_notax_sys
     *
     * @param billamountNotaxSys the value for v_ele_billaccount_payment_info.billamount_notax_sys
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillamountNotaxSys(BigDecimal billamountNotaxSys) {
        this.billamountNotaxSys = billamountNotaxSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.billamount_notax
     *
     * @return the value of v_ele_billaccount_payment_info.billamount_notax
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getBillamountNotax() {
        return billamountNotax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.billamount_notax
     *
     * @param billamountNotax the value for v_ele_billaccount_payment_info.billamount_notax
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillamountNotax(BigDecimal billamountNotax) {
        this.billamountNotax = billamountNotax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.loss_amount_sys
     *
     * @return the value of v_ele_billaccount_payment_info.loss_amount_sys
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getLossAmountSys() {
        return lossAmountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.loss_amount_sys
     *
     * @param lossAmountSys the value for v_ele_billaccount_payment_info.loss_amount_sys
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setLossAmountSys(BigDecimal lossAmountSys) {
        this.lossAmountSys = lossAmountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.loss_amount
     *
     * @return the value of v_ele_billaccount_payment_info.loss_amount
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getLossAmount() {
        return lossAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.loss_amount
     *
     * @param lossAmount the value for v_ele_billaccount_payment_info.loss_amount
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setLossAmount(BigDecimal lossAmount) {
        this.lossAmount = lossAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.billamount_taxamount_sys
     *
     * @return the value of v_ele_billaccount_payment_info.billamount_taxamount_sys
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getBillamountTaxamountSys() {
        return billamountTaxamountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.billamount_taxamount_sys
     *
     * @param billamountTaxamountSys the value for v_ele_billaccount_payment_info.billamount_taxamount_sys
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillamountTaxamountSys(BigDecimal billamountTaxamountSys) {
        this.billamountTaxamountSys = billamountTaxamountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.billamount_taxamount
     *
     * @return the value of v_ele_billaccount_payment_info.billamount_taxamount
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getBillamountTaxamount() {
        return billamountTaxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.billamount_taxamount
     *
     * @param billamountTaxamount the value for v_ele_billaccount_payment_info.billamount_taxamount
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillamountTaxamount(BigDecimal billamountTaxamount) {
        this.billamountTaxamount = billamountTaxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.other_amount
     *
     * @return the value of v_ele_billaccount_payment_info.other_amount
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getOtherAmount() {
        return otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.other_amount
     *
     * @param otherAmount the value for v_ele_billaccount_payment_info.other_amount
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setOtherAmount(BigDecimal otherAmount) {
        this.otherAmount = otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.bill_amount_sys
     *
     * @return the value of v_ele_billaccount_payment_info.bill_amount_sys
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getBillAmountSys() {
        return billAmountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.bill_amount_sys
     *
     * @param billAmountSys the value for v_ele_billaccount_payment_info.bill_amount_sys
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillAmountSys(BigDecimal billAmountSys) {
        this.billAmountSys = billAmountSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.bill_amount_actual
     *
     * @return the value of v_ele_billaccount_payment_info.bill_amount_actual
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getBillAmountActual() {
        return billAmountActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.bill_amount_actual
     *
     * @param billAmountActual the value for v_ele_billaccount_payment_info.bill_amount_actual
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillAmountActual(BigDecimal billAmountActual) {
        this.billAmountActual = billAmountActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.total_degree
     *
     * @return the value of v_ele_billaccount_payment_info.total_degree
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getTotalDegree() {
        return totalDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.total_degree
     *
     * @param totalDegree the value for v_ele_billaccount_payment_info.total_degree
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setTotalDegree(BigDecimal totalDegree) {
        this.totalDegree = totalDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.calc_multi
     *
     * @return the value of v_ele_billaccount_payment_info.calc_multi
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getCalcMulti() {
        return calcMulti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.calc_multi
     *
     * @param calcMulti the value for v_ele_billaccount_payment_info.calc_multi
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setCalcMulti(BigDecimal calcMulti) {
        this.calcMulti = calcMulti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.total_degree_actual
     *
     * @return the value of v_ele_billaccount_payment_info.total_degree_actual
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getTotalDegreeActual() {
        return totalDegreeActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.total_degree_actual
     *
     * @param totalDegreeActual the value for v_ele_billaccount_payment_info.total_degree_actual
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setTotalDegreeActual(BigDecimal totalDegreeActual) {
        this.totalDegreeActual = totalDegreeActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.submit_state
     *
     * @return the value of v_ele_billaccount_payment_info.submit_state
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public Integer getSubmitState() {
        return submitState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.submit_state
     *
     * @param submitState the value for v_ele_billaccount_payment_info.submit_state
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setSubmitState(Integer submitState) {
        this.submitState = submitState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.auditing_state
     *
     * @return the value of v_ele_billaccount_payment_info.auditing_state
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public Integer getAuditingState() {
        return auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.auditing_state
     *
     * @param auditingState the value for v_ele_billaccount_payment_info.auditing_state
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setAuditingState(Integer auditingState) {
        this.auditingState = auditingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.auditing_user_id
     *
     * @return the value of v_ele_billaccount_payment_info.auditing_user_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public String getAuditingUserId() {
        return auditingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.auditing_user_id
     *
     * @param auditingUserId the value for v_ele_billaccount_payment_info.auditing_user_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setAuditingUserId(String auditingUserId) {
        this.auditingUserId = auditingUserId == null ? null : auditingUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.auditing_date
     *
     * @return the value of v_ele_billaccount_payment_info.auditing_date
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8") 
    public Date getAuditingDate() {
        return auditingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.auditing_date
     *
     * @param auditingDate the value for v_ele_billaccount_payment_info.auditing_date
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setAuditingDate(Date auditingDate) {
        this.auditingDate = auditingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.paymentdetail_note
     *
     * @return the value of v_ele_billaccount_payment_info.paymentdetail_note
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public String getPaymentdetailNote() {
        return paymentdetailNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.paymentdetail_note
     *
     * @param paymentdetailNote the value for v_ele_billaccount_payment_info.paymentdetail_note
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setPaymentdetailNote(String paymentdetailNote) {
        this.paymentdetailNote = paymentdetailNote == null ? null : paymentdetailNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.preg_name
     *
     * @return the value of v_ele_billaccount_payment_info.preg_name
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public String getPregName() {
        return pregName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.preg_name
     *
     * @param pregName the value for v_ele_billaccount_payment_info.preg_name
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setPregName(String pregName) {
        this.pregName = pregName == null ? null : pregName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.reg_name
     *
     * @return the value of v_ele_billaccount_payment_info.reg_name
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public String getRegName() {
        return regName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.reg_name
     *
     * @param regName the value for v_ele_billaccount_payment_info.reg_name
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setRegName(String regName) {
        this.regName = regName == null ? null : regName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.preg_id
     *
     * @return the value of v_ele_billaccount_payment_info.preg_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public String getPregId() {
        return pregId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.preg_id
     *
     * @param pregId the value for v_ele_billaccount_payment_info.preg_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setPregId(String pregId) {
        this.pregId = pregId == null ? null : pregId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.reg_id
     *
     * @return the value of v_ele_billaccount_payment_info.reg_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.reg_id
     *
     * @param regId the value for v_ele_billaccount_payment_info.reg_id
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.billaccount_code
     *
     * @return the value of v_ele_billaccount_payment_info.billaccount_code
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public String getBillaccountCode() {
        return billaccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.billaccount_code
     *
     * @param billaccountCode the value for v_ele_billaccount_payment_info.billaccount_code
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillaccountCode(String billaccountCode) {
        this.billaccountCode = billaccountCode == null ? null : billaccountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.billaccount_name
     *
     * @return the value of v_ele_billaccount_payment_info.billaccount_name
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public String getBillaccountName() {
        return billaccountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.billaccount_name
     *
     * @param billaccountName the value for v_ele_billaccount_payment_info.billaccount_name
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setBillaccountName(String billaccountName) {
        this.billaccountName = billaccountName == null ? null : billaccountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.contract_code
     *
     * @return the value of v_ele_billaccount_payment_info.contract_code
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public String getContractCode() {
        return contractCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.contract_code
     *
     * @param contractCode the value for v_ele_billaccount_payment_info.contract_code
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setContractCode(String contractCode) {
        this.contractCode = contractCode == null ? null : contractCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.contract_name
     *
     * @return the value of v_ele_billaccount_payment_info.contract_name
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.contract_name
     *
     * @param contractName the value for v_ele_billaccount_payment_info.contract_name
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_ele_billaccount_payment_info.tax_rate
     *
     * @return the value of v_ele_billaccount_payment_info.tax_rate
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public BigDecimal getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_ele_billaccount_payment_info.tax_rate
     *
     * @param taxRate the value for v_ele_billaccount_payment_info.tax_rate
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    public void setTaxRate(BigDecimal taxRate) {
        this.taxRate = taxRate;
    }
    
    public Act getAct() {
		return act;
	}

	public void setAct(Act act) {
		this.act = act;
	}

	private Act act;
}