package com.xunge.model.selfelec;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VEleBillaccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    public VEleBillaccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBillaccountIdIsNull() {
            addCriterion("billaccount_id is null");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdIsNotNull() {
            addCriterion("billaccount_id is not null");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdEqualTo(String value) {
            addCriterion("billaccount_id =", value, "billaccountId");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdNotEqualTo(String value) {
            addCriterion("billaccount_id <>", value, "billaccountId");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdGreaterThan(String value) {
            addCriterion("billaccount_id >", value, "billaccountId");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("billaccount_id >=", value, "billaccountId");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdLessThan(String value) {
            addCriterion("billaccount_id <", value, "billaccountId");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdLessThanOrEqualTo(String value) {
            addCriterion("billaccount_id <=", value, "billaccountId");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdLike(String value) {
            addCriterion("billaccount_id like", value, "billaccountId");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdNotLike(String value) {
            addCriterion("billaccount_id not like", value, "billaccountId");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdIn(List<String> values) {
            addCriterion("billaccount_id in", values, "billaccountId");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdNotIn(List<String> values) {
            addCriterion("billaccount_id not in", values, "billaccountId");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdBetween(String value1, String value2) {
            addCriterion("billaccount_id between", value1, value2, "billaccountId");
            return (Criteria) this;
        }

        public Criteria andBillaccountIdNotBetween(String value1, String value2) {
            addCriterion("billaccount_id not between", value1, value2, "billaccountId");
            return (Criteria) this;
        }

        public Criteria andPrvIdIsNull() {
            addCriterion("prv_id is null");
            return (Criteria) this;
        }

        public Criteria andPrvIdIsNotNull() {
            addCriterion("prv_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrvIdEqualTo(String value) {
            addCriterion("prv_id =", value, "prvId");
            return (Criteria) this;
        }

        public Criteria andPrvIdNotEqualTo(String value) {
            addCriterion("prv_id <>", value, "prvId");
            return (Criteria) this;
        }

        public Criteria andPrvIdGreaterThan(String value) {
            addCriterion("prv_id >", value, "prvId");
            return (Criteria) this;
        }

        public Criteria andPrvIdGreaterThanOrEqualTo(String value) {
            addCriterion("prv_id >=", value, "prvId");
            return (Criteria) this;
        }

        public Criteria andPrvIdLessThan(String value) {
            addCriterion("prv_id <", value, "prvId");
            return (Criteria) this;
        }

        public Criteria andPrvIdLessThanOrEqualTo(String value) {
            addCriterion("prv_id <=", value, "prvId");
            return (Criteria) this;
        }

        public Criteria andPrvIdLike(String value) {
            addCriterion("prv_id like", value, "prvId");
            return (Criteria) this;
        }

        public Criteria andPrvIdNotLike(String value) {
            addCriterion("prv_id not like", value, "prvId");
            return (Criteria) this;
        }

        public Criteria andPrvIdIn(List<String> values) {
            addCriterion("prv_id in", values, "prvId");
            return (Criteria) this;
        }

        public Criteria andPrvIdNotIn(List<String> values) {
            addCriterion("prv_id not in", values, "prvId");
            return (Criteria) this;
        }

        public Criteria andPrvIdBetween(String value1, String value2) {
            addCriterion("prv_id between", value1, value2, "prvId");
            return (Criteria) this;
        }

        public Criteria andPrvIdNotBetween(String value1, String value2) {
            addCriterion("prv_id not between", value1, value2, "prvId");
            return (Criteria) this;
        }

        public Criteria andPrvSnameIsNull() {
            addCriterion("prv_sname is null");
            return (Criteria) this;
        }

        public Criteria andPrvSnameIsNotNull() {
            addCriterion("prv_sname is not null");
            return (Criteria) this;
        }

        public Criteria andPrvSnameEqualTo(String value) {
            addCriterion("prv_sname =", value, "prvSname");
            return (Criteria) this;
        }

        public Criteria andPrvSnameNotEqualTo(String value) {
            addCriterion("prv_sname <>", value, "prvSname");
            return (Criteria) this;
        }

        public Criteria andPrvSnameGreaterThan(String value) {
            addCriterion("prv_sname >", value, "prvSname");
            return (Criteria) this;
        }

        public Criteria andPrvSnameGreaterThanOrEqualTo(String value) {
            addCriterion("prv_sname >=", value, "prvSname");
            return (Criteria) this;
        }

        public Criteria andPrvSnameLessThan(String value) {
            addCriterion("prv_sname <", value, "prvSname");
            return (Criteria) this;
        }

        public Criteria andPrvSnameLessThanOrEqualTo(String value) {
            addCriterion("prv_sname <=", value, "prvSname");
            return (Criteria) this;
        }

        public Criteria andPrvSnameLike(String value) {
            addCriterion("prv_sname like", value, "prvSname");
            return (Criteria) this;
        }

        public Criteria andPrvSnameNotLike(String value) {
            addCriterion("prv_sname not like", value, "prvSname");
            return (Criteria) this;
        }

        public Criteria andPrvSnameIn(List<String> values) {
            addCriterion("prv_sname in", values, "prvSname");
            return (Criteria) this;
        }

        public Criteria andPrvSnameNotIn(List<String> values) {
            addCriterion("prv_sname not in", values, "prvSname");
            return (Criteria) this;
        }

        public Criteria andPrvSnameBetween(String value1, String value2) {
            addCriterion("prv_sname between", value1, value2, "prvSname");
            return (Criteria) this;
        }

        public Criteria andPrvSnameNotBetween(String value1, String value2) {
            addCriterion("prv_sname not between", value1, value2, "prvSname");
            return (Criteria) this;
        }

        public Criteria andPregIdIsNull() {
            addCriterion("preg_id is null");
            return (Criteria) this;
        }

        public Criteria andPregIdIsNotNull() {
            addCriterion("preg_id is not null");
            return (Criteria) this;
        }

        public Criteria andPregIdEqualTo(String value) {
            addCriterion("preg_id =", value, "pregId");
            return (Criteria) this;
        }

        public Criteria andPregIdNotEqualTo(String value) {
            addCriterion("preg_id <>", value, "pregId");
            return (Criteria) this;
        }

        public Criteria andPregIdGreaterThan(String value) {
            addCriterion("preg_id >", value, "pregId");
            return (Criteria) this;
        }

        public Criteria andPregIdGreaterThanOrEqualTo(String value) {
            addCriterion("preg_id >=", value, "pregId");
            return (Criteria) this;
        }

        public Criteria andPregIdLessThan(String value) {
            addCriterion("preg_id <", value, "pregId");
            return (Criteria) this;
        }

        public Criteria andPregIdLessThanOrEqualTo(String value) {
            addCriterion("preg_id <=", value, "pregId");
            return (Criteria) this;
        }

        public Criteria andPregIdLike(String value) {
            addCriterion("preg_id like", value, "pregId");
            return (Criteria) this;
        }

        public Criteria andPregIdNotLike(String value) {
            addCriterion("preg_id not like", value, "pregId");
            return (Criteria) this;
        }

        public Criteria andPregIdIn(List<String> values) {
            addCriterion("preg_id in", values, "pregId");
            return (Criteria) this;
        }

        public Criteria andPregIdNotIn(List<String> values) {
            addCriterion("preg_id not in", values, "pregId");
            return (Criteria) this;
        }

        public Criteria andPregIdBetween(String value1, String value2) {
            addCriterion("preg_id between", value1, value2, "pregId");
            return (Criteria) this;
        }

        public Criteria andPregIdNotBetween(String value1, String value2) {
            addCriterion("preg_id not between", value1, value2, "pregId");
            return (Criteria) this;
        }

        public Criteria andPregNameIsNull() {
            addCriterion("preg_name is null");
            return (Criteria) this;
        }

        public Criteria andPregNameIsNotNull() {
            addCriterion("preg_name is not null");
            return (Criteria) this;
        }

        public Criteria andPregNameEqualTo(String value) {
            addCriterion("preg_name =", value, "pregName");
            return (Criteria) this;
        }

        public Criteria andPregNameNotEqualTo(String value) {
            addCriterion("preg_name <>", value, "pregName");
            return (Criteria) this;
        }

        public Criteria andPregNameGreaterThan(String value) {
            addCriterion("preg_name >", value, "pregName");
            return (Criteria) this;
        }

        public Criteria andPregNameGreaterThanOrEqualTo(String value) {
            addCriterion("preg_name >=", value, "pregName");
            return (Criteria) this;
        }

        public Criteria andPregNameLessThan(String value) {
            addCriterion("preg_name <", value, "pregName");
            return (Criteria) this;
        }

        public Criteria andPregNameLessThanOrEqualTo(String value) {
            addCriterion("preg_name <=", value, "pregName");
            return (Criteria) this;
        }

        public Criteria andPregNameLike(String value) {
            addCriterion("preg_name like", value, "pregName");
            return (Criteria) this;
        }

        public Criteria andPregNameNotLike(String value) {
            addCriterion("preg_name not like", value, "pregName");
            return (Criteria) this;
        }

        public Criteria andPregNameIn(List<String> values) {
            addCriterion("preg_name in", values, "pregName");
            return (Criteria) this;
        }

        public Criteria andPregNameNotIn(List<String> values) {
            addCriterion("preg_name not in", values, "pregName");
            return (Criteria) this;
        }

        public Criteria andPregNameBetween(String value1, String value2) {
            addCriterion("preg_name between", value1, value2, "pregName");
            return (Criteria) this;
        }

        public Criteria andPregNameNotBetween(String value1, String value2) {
            addCriterion("preg_name not between", value1, value2, "pregName");
            return (Criteria) this;
        }

        public Criteria andRegIdIsNull() {
            addCriterion("reg_id is null");
            return (Criteria) this;
        }

        public Criteria andRegIdIsNotNull() {
            addCriterion("reg_id is not null");
            return (Criteria) this;
        }

        public Criteria andRegIdEqualTo(String value) {
            addCriterion("reg_id =", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotEqualTo(String value) {
            addCriterion("reg_id <>", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdGreaterThan(String value) {
            addCriterion("reg_id >", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdGreaterThanOrEqualTo(String value) {
            addCriterion("reg_id >=", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdLessThan(String value) {
            addCriterion("reg_id <", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdLessThanOrEqualTo(String value) {
            addCriterion("reg_id <=", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdLike(String value) {
            addCriterion("reg_id like", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotLike(String value) {
            addCriterion("reg_id not like", value, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdIn(List<String> values) {
            addCriterion("reg_id in", values, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotIn(List<String> values) {
            addCriterion("reg_id not in", values, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdBetween(String value1, String value2) {
            addCriterion("reg_id between", value1, value2, "regId");
            return (Criteria) this;
        }

        public Criteria andRegIdNotBetween(String value1, String value2) {
            addCriterion("reg_id not between", value1, value2, "regId");
            return (Criteria) this;
        }

        public Criteria andRegNameIsNull() {
            addCriterion("reg_name is null");
            return (Criteria) this;
        }

        public Criteria andRegNameIsNotNull() {
            addCriterion("reg_name is not null");
            return (Criteria) this;
        }

        public Criteria andRegNameEqualTo(String value) {
            addCriterion("reg_name =", value, "regName");
            return (Criteria) this;
        }

        public Criteria andRegNameNotEqualTo(String value) {
            addCriterion("reg_name <>", value, "regName");
            return (Criteria) this;
        }

        public Criteria andRegNameGreaterThan(String value) {
            addCriterion("reg_name >", value, "regName");
            return (Criteria) this;
        }

        public Criteria andRegNameGreaterThanOrEqualTo(String value) {
            addCriterion("reg_name >=", value, "regName");
            return (Criteria) this;
        }

        public Criteria andRegNameLessThan(String value) {
            addCriterion("reg_name <", value, "regName");
            return (Criteria) this;
        }

        public Criteria andRegNameLessThanOrEqualTo(String value) {
            addCriterion("reg_name <=", value, "regName");
            return (Criteria) this;
        }

        public Criteria andRegNameLike(String value) {
            addCriterion("reg_name like", value, "regName");
            return (Criteria) this;
        }

        public Criteria andRegNameNotLike(String value) {
            addCriterion("reg_name not like", value, "regName");
            return (Criteria) this;
        }

        public Criteria andRegNameIn(List<String> values) {
            addCriterion("reg_name in", values, "regName");
            return (Criteria) this;
        }

        public Criteria andRegNameNotIn(List<String> values) {
            addCriterion("reg_name not in", values, "regName");
            return (Criteria) this;
        }

        public Criteria andRegNameBetween(String value1, String value2) {
            addCriterion("reg_name between", value1, value2, "regName");
            return (Criteria) this;
        }

        public Criteria andRegNameNotBetween(String value1, String value2) {
            addCriterion("reg_name not between", value1, value2, "regName");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeIsNull() {
            addCriterion("billaccount_code is null");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeIsNotNull() {
            addCriterion("billaccount_code is not null");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeEqualTo(String value) {
            addCriterion("billaccount_code =", value, "billaccountCode");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeNotEqualTo(String value) {
            addCriterion("billaccount_code <>", value, "billaccountCode");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeGreaterThan(String value) {
            addCriterion("billaccount_code >", value, "billaccountCode");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeGreaterThanOrEqualTo(String value) {
            addCriterion("billaccount_code >=", value, "billaccountCode");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeLessThan(String value) {
            addCriterion("billaccount_code <", value, "billaccountCode");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeLessThanOrEqualTo(String value) {
            addCriterion("billaccount_code <=", value, "billaccountCode");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeLike(String value) {
            addCriterion("billaccount_code like '%%'",value,"billaccountCode");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeNotLike(String value) {
            addCriterion("billaccount_code not like", value, "billaccountCode");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeIn(List<String> values) {
            addCriterion("billaccount_code in", values, "billaccountCode");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeNotIn(List<String> values) {
            addCriterion("billaccount_code not in", values, "billaccountCode");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeBetween(String value1, String value2) {
            addCriterion("billaccount_code between", value1, value2, "billaccountCode");
            return (Criteria) this;
        }

        public Criteria andBillaccountCodeNotBetween(String value1, String value2) {
            addCriterion("billaccount_code not between", value1, value2, "billaccountCode");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameIsNull() {
            addCriterion("billaccount_name is null");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameIsNotNull() {
            addCriterion("billaccount_name is not null");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameEqualTo(String value) {
            addCriterion("billaccount_name =", value, "billaccountName");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameNotEqualTo(String value) {
            addCriterion("billaccount_name <>", value, "billaccountName");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameGreaterThan(String value) {
            addCriterion("billaccount_name >", value, "billaccountName");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameGreaterThanOrEqualTo(String value) {
            addCriterion("billaccount_name >=", value, "billaccountName");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameLessThan(String value) {
            addCriterion("billaccount_name <", value, "billaccountName");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameLessThanOrEqualTo(String value) {
            addCriterion("billaccount_name <=", value, "billaccountName");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameLike(String value) {
            addCriterion("billaccount_name like '%%'",value,"billaccountName");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameNotLike(String value) {
            addCriterion("billaccount_name not like", value, "billaccountName");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameIn(List<String> values) {
            addCriterion("billaccount_name in", values, "billaccountName");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameNotIn(List<String> values) {
            addCriterion("billaccount_name not in", values, "billaccountName");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameBetween(String value1, String value2) {
            addCriterion("billaccount_name between", value1, value2, "billaccountName");
            return (Criteria) this;
        }

        public Criteria andBillaccountNameNotBetween(String value1, String value2) {
            addCriterion("billaccount_name not between", value1, value2, "billaccountName");
            return (Criteria) this;
        }

        public Criteria andBillaccountStateIsNull() {
            addCriterion("billaccount_state is null");
            return (Criteria) this;
        }

        public Criteria andBillaccountStateIsNotNull() {
            addCriterion("billaccount_state is not null");
            return (Criteria) this;
        }

        public Criteria andBillaccountStateEqualTo(Integer value) {
            addCriterion("billaccount_state =", value, "billaccountState");
            return (Criteria) this;
        }

        public Criteria andBillaccountStateNotEqualTo(Integer value) {
            addCriterion("billaccount_state <>", value, "billaccountState");
            return (Criteria) this;
        }

        public Criteria andBillaccountStateGreaterThan(Integer value) {
            addCriterion("billaccount_state >", value, "billaccountState");
            return (Criteria) this;
        }

        public Criteria andBillaccountStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("billaccount_state >=", value, "billaccountState");
            return (Criteria) this;
        }

        public Criteria andBillaccountStateLessThan(Integer value) {
            addCriterion("billaccount_state <", value, "billaccountState");
            return (Criteria) this;
        }

        public Criteria andBillaccountStateLessThanOrEqualTo(Integer value) {
            addCriterion("billaccount_state <=", value, "billaccountState");
            return (Criteria) this;
        }

        public Criteria andBillaccountStateIn(List<Integer> values) {
            addCriterion("billaccount_state in", values, "billaccountState");
            return (Criteria) this;
        }

        public Criteria andBillaccountStateNotIn(List<Integer> values) {
            addCriterion("billaccount_state not in", values, "billaccountState");
            return (Criteria) this;
        }

        public Criteria andBillaccountStateBetween(Integer value1, Integer value2) {
            addCriterion("billaccount_state between", value1, value2, "billaccountState");
            return (Criteria) this;
        }

        public Criteria andBillaccountStateNotBetween(Integer value1, Integer value2) {
            addCriterion("billaccount_state not between", value1, value2, "billaccountState");
            return (Criteria) this;
        }

        public Criteria andBillaccountTypeIsNull() {
            addCriterion("billaccount_type is null");
            return (Criteria) this;
        }

        public Criteria andBillaccountTypeIsNotNull() {
            addCriterion("billaccount_type is not null");
            return (Criteria) this;
        }

        public Criteria andBillaccountTypeEqualTo(Integer value) {
            addCriterion("billaccount_type =", value, "billaccountType");
            return (Criteria) this;
        }

        public Criteria andBillaccountTypeNotEqualTo(Integer value) {
            addCriterion("billaccount_type <>", value, "billaccountType");
            return (Criteria) this;
        }

        public Criteria andBillaccountTypeGreaterThan(Integer value) {
            addCriterion("billaccount_type >", value, "billaccountType");
            return (Criteria) this;
        }

        public Criteria andBillaccountTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("billaccount_type >=", value, "billaccountType");
            return (Criteria) this;
        }

        public Criteria andBillaccountTypeLessThan(Integer value) {
            addCriterion("billaccount_type <", value, "billaccountType");
            return (Criteria) this;
        }

        public Criteria andBillaccountTypeLessThanOrEqualTo(Integer value) {
            addCriterion("billaccount_type <=", value, "billaccountType");
            return (Criteria) this;
        }

        public Criteria andBillaccountTypeIn(List<Integer> values) {
            addCriterion("billaccount_type in", values, "billaccountType");
            return (Criteria) this;
        }

        public Criteria andBillaccountTypeNotIn(List<Integer> values) {
            addCriterion("billaccount_type not in", values, "billaccountType");
            return (Criteria) this;
        }

        public Criteria andBillaccountTypeBetween(Integer value1, Integer value2) {
            addCriterion("billaccount_type between", value1, value2, "billaccountType");
            return (Criteria) this;
        }

        public Criteria andBillaccountTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("billaccount_type not between", value1, value2, "billaccountType");
            return (Criteria) this;
        }

        public Criteria andAuditingStateIsNull() {
            addCriterion("auditing_state is null");
            return (Criteria) this;
        }

        public Criteria andAuditingStateIsNotNull() {
            addCriterion("auditing_state is not null");
            return (Criteria) this;
        }

        public Criteria andAuditingStateEqualTo(Integer value) {
            addCriterion("auditing_state =", value, "auditingState");
            return (Criteria) this;
        }

        public Criteria andAuditingStateNotEqualTo(Integer value) {
            addCriterion("auditing_state <>", value, "auditingState");
            return (Criteria) this;
        }

        public Criteria andAuditingStateGreaterThan(Integer value) {
            addCriterion("auditing_state >", value, "auditingState");
            return (Criteria) this;
        }

        public Criteria andAuditingStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("auditing_state >=", value, "auditingState");
            return (Criteria) this;
        }

        public Criteria andAuditingStateLessThan(Integer value) {
            addCriterion("auditing_state <", value, "auditingState");
            return (Criteria) this;
        }

        public Criteria andAuditingStateLessThanOrEqualTo(Integer value) {
            addCriterion("auditing_state <=", value, "auditingState");
            return (Criteria) this;
        }

        public Criteria andAuditingStateIn(List<Integer> values) {
            addCriterion("auditing_state in", values, "auditingState");
            return (Criteria) this;
        }

        public Criteria andAuditingStateNotIn(List<Integer> values) {
            addCriterion("auditing_state not in", values, "auditingState");
            return (Criteria) this;
        }

        public Criteria andAuditingStateBetween(Integer value1, Integer value2) {
            addCriterion("auditing_state between", value1, value2, "auditingState");
            return (Criteria) this;
        }

        public Criteria andAuditingStateNotBetween(Integer value1, Integer value2) {
            addCriterion("auditing_state not between", value1, value2, "auditingState");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdIsNull() {
            addCriterion("auditing_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdIsNotNull() {
            addCriterion("auditing_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdEqualTo(String value) {
            addCriterion("auditing_user_id =", value, "auditingUserId");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdNotEqualTo(String value) {
            addCriterion("auditing_user_id <>", value, "auditingUserId");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdGreaterThan(String value) {
            addCriterion("auditing_user_id >", value, "auditingUserId");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("auditing_user_id >=", value, "auditingUserId");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdLessThan(String value) {
            addCriterion("auditing_user_id <", value, "auditingUserId");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdLessThanOrEqualTo(String value) {
            addCriterion("auditing_user_id <=", value, "auditingUserId");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdLike(String value) {
            addCriterion("auditing_user_id like", value, "auditingUserId");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdNotLike(String value) {
            addCriterion("auditing_user_id not like", value, "auditingUserId");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdIn(List<String> values) {
            addCriterion("auditing_user_id in", values, "auditingUserId");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdNotIn(List<String> values) {
            addCriterion("auditing_user_id not in", values, "auditingUserId");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdBetween(String value1, String value2) {
            addCriterion("auditing_user_id between", value1, value2, "auditingUserId");
            return (Criteria) this;
        }

        public Criteria andAuditingUserIdNotBetween(String value1, String value2) {
            addCriterion("auditing_user_id not between", value1, value2, "auditingUserId");
            return (Criteria) this;
        }

        public Criteria andAuditingDateIsNull() {
            addCriterion("auditing_date is null");
            return (Criteria) this;
        }

        public Criteria andAuditingDateIsNotNull() {
            addCriterion("auditing_date is not null");
            return (Criteria) this;
        }

        public Criteria andAuditingDateEqualTo(Date value) {
            addCriterion("auditing_date =", value, "auditingDate");
            return (Criteria) this;
        }

        public Criteria andAuditingDateNotEqualTo(Date value) {
            addCriterion("auditing_date <>", value, "auditingDate");
            return (Criteria) this;
        }

        public Criteria andAuditingDateGreaterThan(Date value) {
            addCriterion("auditing_date >", value, "auditingDate");
            return (Criteria) this;
        }

        public Criteria andAuditingDateGreaterThanOrEqualTo(Date value) {
            addCriterion("auditing_date >=", value, "auditingDate");
            return (Criteria) this;
        }

        public Criteria andAuditingDateLessThan(Date value) {
            addCriterion("auditing_date <", value, "auditingDate");
            return (Criteria) this;
        }

        public Criteria andAuditingDateLessThanOrEqualTo(Date value) {
            addCriterion("auditing_date <=", value, "auditingDate");
            return (Criteria) this;
        }

        public Criteria andAuditingDateIn(List<Date> values) {
            addCriterion("auditing_date in", values, "auditingDate");
            return (Criteria) this;
        }

        public Criteria andAuditingDateNotIn(List<Date> values) {
            addCriterion("auditing_date not in", values, "auditingDate");
            return (Criteria) this;
        }

        public Criteria andAuditingDateBetween(Date value1, Date value2) {
            addCriterion("auditing_date between", value1, value2, "auditingDate");
            return (Criteria) this;
        }

        public Criteria andAuditingDateNotBetween(Date value1, Date value2) {
            addCriterion("auditing_date not between", value1, value2, "auditingDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateIsNull() {
            addCriterion("plan_date is null");
            return (Criteria) this;
        }

        public Criteria andPlanDateIsNotNull() {
            addCriterion("plan_date is not null");
            return (Criteria) this;
        }

        public Criteria andPlanDateEqualTo(Date value) {
            addCriterion("plan_date =", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateNotEqualTo(Date value) {
            addCriterion("plan_date <>", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateGreaterThan(Date value) {
            addCriterion("plan_date >", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateGreaterThanOrEqualTo(Date value) {
            addCriterion("plan_date >=", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateLessThan(Date value) {
            addCriterion("plan_date <", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateLessThanOrEqualTo(Date value) {
            addCriterion("plan_date <=", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateIn(List<Date> values) {
            addCriterion("plan_date in", values, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateNotIn(List<Date> values) {
            addCriterion("plan_date not in", values, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateBetween(Date value1, Date value2) {
            addCriterion("plan_date between", value1, value2, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateNotBetween(Date value1, Date value2) {
            addCriterion("plan_date not between", value1, value2, "planDate");
            return (Criteria) this;
        }

        public Criteria andCalcMultiIsNull() {
            addCriterion("calc_multi is null");
            return (Criteria) this;
        }

        public Criteria andCalcMultiIsNotNull() {
            addCriterion("calc_multi is not null");
            return (Criteria) this;
        }

        public Criteria andCalcMultiEqualTo(BigDecimal value) {
            addCriterion("calc_multi =", value, "calcMulti");
            return (Criteria) this;
        }

        public Criteria andCalcMultiNotEqualTo(BigDecimal value) {
            addCriterion("calc_multi <>", value, "calcMulti");
            return (Criteria) this;
        }

        public Criteria andCalcMultiGreaterThan(BigDecimal value) {
            addCriterion("calc_multi >", value, "calcMulti");
            return (Criteria) this;
        }

        public Criteria andCalcMultiGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("calc_multi >=", value, "calcMulti");
            return (Criteria) this;
        }

        public Criteria andCalcMultiLessThan(BigDecimal value) {
            addCriterion("calc_multi <", value, "calcMulti");
            return (Criteria) this;
        }

        public Criteria andCalcMultiLessThanOrEqualTo(BigDecimal value) {
            addCriterion("calc_multi <=", value, "calcMulti");
            return (Criteria) this;
        }

        public Criteria andCalcMultiIn(List<BigDecimal> values) {
            addCriterion("calc_multi in", values, "calcMulti");
            return (Criteria) this;
        }

        public Criteria andCalcMultiNotIn(List<BigDecimal> values) {
            addCriterion("calc_multi not in", values, "calcMulti");
            return (Criteria) this;
        }

        public Criteria andCalcMultiBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("calc_multi between", value1, value2, "calcMulti");
            return (Criteria) this;
        }

        public Criteria andCalcMultiNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("calc_multi not between", value1, value2, "calcMulti");
            return (Criteria) this;
        }

        public Criteria andPaymentStateIsNull() {
            addCriterion("payment_state is null");
            return (Criteria) this;
        }

        public Criteria andPaymentStateIsNotNull() {
            addCriterion("payment_state is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentStateEqualTo(Integer value) {
            addCriterion("payment_state =", value, "paymentState");
            return (Criteria) this;
        }

        public Criteria andPaymentStateNotEqualTo(Integer value) {
            addCriterion("payment_state <>", value, "paymentState");
            return (Criteria) this;
        }

        public Criteria andPaymentStateGreaterThan(Integer value) {
            addCriterion("payment_state >", value, "paymentState");
            return (Criteria) this;
        }

        public Criteria andPaymentStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("payment_state >=", value, "paymentState");
            return (Criteria) this;
        }

        public Criteria andPaymentStateLessThan(Integer value) {
            addCriterion("payment_state <", value, "paymentState");
            return (Criteria) this;
        }

        public Criteria andPaymentStateLessThanOrEqualTo(Integer value) {
            addCriterion("payment_state <=", value, "paymentState");
            return (Criteria) this;
        }

        public Criteria andPaymentStateIn(List<Integer> values) {
            addCriterion("payment_state in", values, "paymentState");
            return (Criteria) this;
        }

        public Criteria andPaymentStateNotIn(List<Integer> values) {
            addCriterion("payment_state not in", values, "paymentState");
            return (Criteria) this;
        }

        public Criteria andPaymentStateBetween(Integer value1, Integer value2) {
            addCriterion("payment_state between", value1, value2, "paymentState");
            return (Criteria) this;
        }

        public Criteria andPaymentStateNotBetween(Integer value1, Integer value2) {
            addCriterion("payment_state not between", value1, value2, "paymentState");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteIsNull() {
            addCriterion("billaccount_note is null");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteIsNotNull() {
            addCriterion("billaccount_note is not null");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteEqualTo(String value) {
            addCriterion("billaccount_note =", value, "billaccountNote");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteNotEqualTo(String value) {
            addCriterion("billaccount_note <>", value, "billaccountNote");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteGreaterThan(String value) {
            addCriterion("billaccount_note >", value, "billaccountNote");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteGreaterThanOrEqualTo(String value) {
            addCriterion("billaccount_note >=", value, "billaccountNote");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteLessThan(String value) {
            addCriterion("billaccount_note <", value, "billaccountNote");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteLessThanOrEqualTo(String value) {
            addCriterion("billaccount_note <=", value, "billaccountNote");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteLike(String value) {
            addCriterion("billaccount_note like", value, "billaccountNote");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteNotLike(String value) {
            addCriterion("billaccount_note not like", value, "billaccountNote");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteIn(List<String> values) {
            addCriterion("billaccount_note in", values, "billaccountNote");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteNotIn(List<String> values) {
            addCriterion("billaccount_note not in", values, "billaccountNote");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteBetween(String value1, String value2) {
            addCriterion("billaccount_note between", value1, value2, "billaccountNote");
            return (Criteria) this;
        }

        public Criteria andBillaccountNoteNotBetween(String value1, String value2) {
            addCriterion("billaccount_note not between", value1, value2, "billaccountNote");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated do_not_delete_during_merge Sat Jul 15 11:30:31 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}