package com.xunge.dao.basedata;

import com.xunge.model.basedata.DatBasesite;
import com.xunge.model.basedata.DatBasesiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DatBasesiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_basesite
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int countByExample(DatBasesiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_basesite
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int deleteByExample(DatBasesiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_basesite
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int deleteByPrimaryKey(String basesiteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_basesite
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int insert(DatBasesite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_basesite
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int insertSelective(DatBasesite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_basesite
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    List<DatBasesite> selectByExample(DatBasesiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_basesite
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    DatBasesite selectByPrimaryKey(String basesiteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_basesite
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") DatBasesite record, @Param("example") DatBasesiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_basesite
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int updateByExample(@Param("record") DatBasesite record, @Param("example") DatBasesiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_basesite
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int updateByPrimaryKeySelective(DatBasesite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_basesite
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int updateByPrimaryKey(DatBasesite record);
}