package com.xunge.dao.selfelec;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.xunge.model.selfelec.EleBenchmarkBillaccountBean;
import com.xunge.model.selfelec.EleBillaccount;
import com.xunge.model.selfelec.EleBillaccountExample;

public interface EleBillaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int countByExample(EleBillaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int deleteByExample(EleBillaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int deleteByPrimaryKey(String billaccountId);
    
    /**
     * @description 删除报账点与合同关联关系
     * @author yuefy
     * @date 创建时间：2017年8月30日
     */
    public int deleteBillaccountContract(Map<String, Object> paraMap);
    
    /**
     * @description 删除报账点与资源关联关系
     * @author yuefy
     * @date 创建时间：2017年8月30日
     */
    public int deleteBillaccountResource(Map<String, Object> paraMap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int insert(EleBillaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int insertSelective(EleBillaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    List<EleBillaccount> selectByExample(EleBillaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    EleBillaccount selectByPrimaryKey(String billaccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByExampleSelective(@Param("record") EleBillaccount record, @Param("example") EleBillaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByExample(@Param("record") EleBillaccount record, @Param("example") EleBillaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByPrimaryKeySelective(EleBillaccount record);
   
   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByPrimaryKey(EleBillaccount record);
    
    /**
     * 修改流程状态
     * @param hashMaps
     * @return
     * @author xup
     */
    int updateActivityCommit(Map<String,Object> hashMaps);
    
    /**
     * 查询报账点审核页面
     * @param hashMaps
     * @return
     * @author xup
     */
	public List<EleBillaccount> queryEleBillaccount(Map<String,Object> hashMaps);
	/**
	 * 根据报账点id查询报账点信息
	 * @param hashMaps
	 * @return
	 */
	public List<EleBillaccount> queryBillaccountById(Map<String,Object> hashMaps);
    
	/**
	 * 报账标杆分页数据查询
	 * @author wangz
	 * @param paramMap
	 * @return
	 */
	public List<EleBenchmarkBillaccountBean> queryPageEleBillBenchmark(Map<String,Object> paramMap);
	
	/**
	 * 报账标杆数据查询
	 * @author wangz
	 * @param paramMap
	 * @return
	 */
	public List<EleBenchmarkBillaccountBean> queryEleBillBenchmark(Map<String,Object> paramMap);
	
	int updateStateByPrimaryKey(String billaccountId);
	
	/**
	 * 根据报账点id查询计划缴费日期
	 * @param billaccountId
	 * @return
	 */
	public List<EleBillaccount> queryEleBillaccountById(Map<String,Object> paramMap);
	
	public  int updatePlanDateById(Map<String,Object> paramMap);
}