package com.xunge.dao.selfelec;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.xunge.model.selfelec.EleBillaccountPaymentdetail;
import com.xunge.model.selfelec.EleBillaccountPaymentdetailExample;
import com.xunge.model.selfelec.VEleBillaccountPaymentInfo;

public interface EleBillaccountPaymentdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount_paymentdetail
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    int countByExample(EleBillaccountPaymentdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount_paymentdetail
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    int deleteByExample(EleBillaccountPaymentdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount_paymentdetail
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    int deleteByPrimaryKey(String billaccountpaymentdetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount_paymentdetail
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    int insert(EleBillaccountPaymentdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount_paymentdetail
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    int insertSelective(EleBillaccountPaymentdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount_paymentdetail
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    List<EleBillaccountPaymentdetail> selectByExample(EleBillaccountPaymentdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount_paymentdetail
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    EleBillaccountPaymentdetail selectByPrimaryKey(String billaccountpaymentdetailId);
    
    /**
     * 根据id查询信息
     * @param billaccountpaymentdetailId
     * @return
     * @author xup
     */
    public  EleBillaccountPaymentdetail queryById(String billaccountpaymentdetailId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount_paymentdetail
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") EleBillaccountPaymentdetail record, @Param("example") EleBillaccountPaymentdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount_paymentdetail
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    int updateByExample(@Param("record") EleBillaccountPaymentdetail record, @Param("example") EleBillaccountPaymentdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount_paymentdetail
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    int updateByPrimaryKeySelective(EleBillaccountPaymentdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccount_paymentdetail
     *
     * @mbggenerated Sat Jul 22 22:33:19 CST 2017
     */
    int updateByPrimaryKey(EleBillaccountPaymentdetail record);
    
    /**
     * 修改流程状态
     * @param hashMaps
     * @return
     * @author xup
     */
    int updateActivityCommit(Map<String,Object> hashMaps);
    
    int updatePaymentState(Map<String,Object> hashMap);
    /**
     * 根据报账点id查询缴费记录信息
     * @author xup
     */
    List<EleBillaccountPaymentdetail> queryPaymentByBillAccountId(String id);
	/**
	 * 根据报账点编码查询此最大缴费期终的信息
	 * @param paraMap
	 * @return
	 */
	public VEleBillaccountPaymentInfo queryMaxBillAccountEnded(String billaccountId);
}