package com.xunge.dao.selfelec;

import com.xunge.model.selfelec.EleBaseresourceelectricmeter;
import com.xunge.model.selfelec.EleBaseresourceelectricmeterExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface EleBaseresourceelectricmeterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int countByExample(EleBaseresourceelectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int deleteByExample(EleBaseresourceelectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int deleteByPrimaryKey(String baseresourceelectricmeterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int insert(EleBaseresourceelectricmeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int insertSelective(EleBaseresourceelectricmeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    List<EleBaseresourceelectricmeter> selectByExample(EleBaseresourceelectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    EleBaseresourceelectricmeter selectByPrimaryKey(String baseresourceelectricmeterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByExampleSelective(@Param("record") EleBaseresourceelectricmeter record, @Param("example") EleBaseresourceelectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByExample(@Param("record") EleBaseresourceelectricmeter record, @Param("example") EleBaseresourceelectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByPrimaryKeySelective(EleBaseresourceelectricmeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByPrimaryKey(EleBaseresourceelectricmeter record);
    /**
     * 删除资源点与电表关联关系
     * @param paraMap
     * @return
     */
    int deleteRescoureMeter(Map<String, Object> paraMap);
    
    /**根据报账点编码获取资源点编码
     * @param billaccountId
     * @return
     */
    List<String> queryBaseresourceIdByBillaccountId(String billaccountId);
}