package com.xunge.dao.selfelec;

import com.xunge.model.selfelec.EleBillaccountbaseresource;
import com.xunge.model.selfelec.EleBillaccountbaseresourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EleBillaccountbaseresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccountbaseresource
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int countByExample(EleBillaccountbaseresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccountbaseresource
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int deleteByExample(EleBillaccountbaseresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccountbaseresource
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int deleteByPrimaryKey(String billaccountbaseresourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccountbaseresource
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int insert(EleBillaccountbaseresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccountbaseresource
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int insertSelective(EleBillaccountbaseresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccountbaseresource
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    List<EleBillaccountbaseresource> selectByExample(EleBillaccountbaseresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccountbaseresource
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    EleBillaccountbaseresource selectByPrimaryKey(String billaccountbaseresourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccountbaseresource
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByExampleSelective(@Param("record") EleBillaccountbaseresource record, @Param("example") EleBillaccountbaseresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccountbaseresource
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByExample(@Param("record") EleBillaccountbaseresource record, @Param("example") EleBillaccountbaseresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccountbaseresource
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByPrimaryKeySelective(EleBillaccountbaseresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_billaccountbaseresource
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByPrimaryKey(EleBillaccountbaseresource record);
}