package com.xunge.dao.selfelec;

import com.xunge.model.selfelec.EleContractCollection;
import com.xunge.model.selfelec.EleContractCollectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EleContractCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_contract_collection
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int countByExample(EleContractCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_contract_collection
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int deleteByExample(EleContractCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_contract_collection
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int deleteByPrimaryKey(String elecontractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_contract_collection
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int insert(EleContractCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_contract_collection
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int insertSelective(EleContractCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_contract_collection
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    List<EleContractCollection> selectByExample(EleContractCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_contract_collection
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    EleContractCollection selectByPrimaryKey(String elecontractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_contract_collection
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByExampleSelective(@Param("record") EleContractCollection record, @Param("example") EleContractCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_contract_collection
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByExample(@Param("record") EleContractCollection record, @Param("example") EleContractCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_contract_collection
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByPrimaryKeySelective(EleContractCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_contract_collection
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByPrimaryKey(EleContractCollection record);
}