package com.xunge.dao.selfelec;

import com.xunge.model.selfelec.VDatElectricmeter;
import com.xunge.model.selfelec.VDatElectricmeterExample;
import com.xunge.model.selfelec.VDatElectricmeterWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VDatElectricmeterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_electricmeter
     *
     * @mbggenerated Wed Aug 09 23:39:01 CST 2017
     */
    int countByExample(VDatElectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_electricmeter
     *
     * @mbggenerated Wed Aug 09 23:39:01 CST 2017
     */
    int deleteByExample(VDatElectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_electricmeter
     *
     * @mbggenerated Wed Aug 09 23:39:01 CST 2017
     */
    int insert(VDatElectricmeterWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_electricmeter
     *
     * @mbggenerated Wed Aug 09 23:39:01 CST 2017
     */
    int insertSelective(VDatElectricmeterWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_electricmeter
     *
     * @mbggenerated Wed Aug 09 23:39:01 CST 2017
     */
    List<VDatElectricmeterWithBLOBs> selectByExampleWithBLOBs(VDatElectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_electricmeter
     *
     * @mbggenerated Wed Aug 09 23:39:01 CST 2017
     */
    List<VDatElectricmeter> selectByExample(VDatElectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_electricmeter
     *
     * @mbggenerated Wed Aug 09 23:39:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") VDatElectricmeterWithBLOBs record, @Param("example") VDatElectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_electricmeter
     *
     * @mbggenerated Wed Aug 09 23:39:01 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") VDatElectricmeterWithBLOBs record, @Param("example") VDatElectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_electricmeter
     *
     * @mbggenerated Wed Aug 09 23:39:01 CST 2017
     */
    int updateByExample(@Param("record") VDatElectricmeter record, @Param("example") VDatElectricmeterExample example);
}