package com.xunge.dao.selfelec;

import com.xunge.model.selfelec.VDatBaseresourceBe;
import com.xunge.model.selfelec.VDatBaseresourceBeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VDatBaseresourceBeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_baseresource_be
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    int countByExample(VDatBaseresourceBeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_baseresource_be
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    int deleteByExample(VDatBaseresourceBeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_baseresource_be
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    int insert(VDatBaseresourceBe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_baseresource_be
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    int insertSelective(VDatBaseresourceBe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_baseresource_be
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    List<VDatBaseresourceBe> selectByExample(VDatBaseresourceBeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_baseresource_be
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") VDatBaseresourceBe record, @Param("example") VDatBaseresourceBeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_baseresource_be
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    int updateByExample(@Param("record") VDatBaseresourceBe record, @Param("example") VDatBaseresourceBeExample example);
}