package com.xunge.dao.selfelec;

import com.xunge.model.selfelec.VDatContract;
import com.xunge.model.selfelec.VDatContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VDatContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_contract
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    int countByExample(VDatContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_contract
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    int deleteByExample(VDatContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_contract
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    int insert(VDatContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_contract
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    int insertSelective(VDatContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_contract
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    List<VDatContract> selectByExample(VDatContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_contract
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") VDatContract record, @Param("example") VDatContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_dat_contract
     *
     * @mbggenerated Sun Jul 02 14:57:09 CST 2017
     */
    int updateByExample(@Param("record") VDatContract record, @Param("example") VDatContractExample example);
}