package com.xunge.dao.selfelec;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.xunge.model.selfelec.VEleContract;
import com.xunge.model.selfelec.VEleContractCuring;
import com.xunge.model.selfelec.VEleContractExample;

public interface VEleContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_contract
     *
     * @mbggenerated Mon Jul 17 13:43:30 CST 2017
     */
    int countByExample(VEleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_contract
     *
     * @mbggenerated Mon Jul 17 13:43:30 CST 2017
     */
    int deleteByExample(VEleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_contract
     *
     * @mbggenerated Mon Jul 17 13:43:30 CST 2017
     */
    int insert(VEleContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_contract
     *
     * @mbggenerated Mon Jul 17 13:43:30 CST 2017
     */
    int insertSelective(VEleContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_contract
     *
     * @mbggenerated Mon Jul 17 13:43:30 CST 2017
     */
    List<VEleContract> selectByExample(VEleContractExample example);
    List<VEleContract> selectByExample(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_contract
     *
     * @mbggenerated Mon Jul 17 13:43:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") VEleContract record, @Param("example") VEleContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_contract
     *
     * @mbggenerated Mon Jul 17 13:43:30 CST 2017
     */
    int updateByExample(@Param("record") VEleContract record, @Param("example") VEleContractExample example);
    
    List<VEleContract> queryAllElecContract(Map<String, Object> paramMap);
    
    List<VEleContractCuring> queryAllElecContractCuring(Map<String, Object> paramMap);
    
    VEleContract queryVEleContractVOById(String eleconstractId);
    
    int updateContractVO(Map<String, Object> paramMap);
    
    VEleContract queryOneElecContractById(String eleconstractId);

    /**
     * @description 根据电费合同id查询此条合同最终缴费日期
     * @author yuefy
     * @date 创建时间：2017年9月7日
     */
	public String getElePaymentEnddate(Map<String, Object> paraMap);

	/**
	 * @description 查询报账点和合同关联表信息
	 * @author yuefy
	 * @date 创建时间：2017年9月8日
	 */
	List<String> queryBillaccountContract(Map<String, Object> map);

	/**
	 * @description 批量修改合同状态
	 * @author yuefy
	 * @date 创建时间：2017年10月19日
	 */
	public boolean updateContractState(Map<String, Object> paramMap);
}