package com.xunge.dao.selfelec;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.xunge.model.selfelec.VEleBillaccount;
import com.xunge.model.selfelec.VEleBillaccountExample;

public interface VEleBillaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    int countByExample(VEleBillaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    int deleteByExample(VEleBillaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    int insert(VEleBillaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    int insertSelective(VEleBillaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    List<VEleBillaccount> selectByExample(VEleBillaccountExample example);
    List<VEleBillaccount> selectByExample(Map<String ,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") VEleBillaccount record, @Param("example") VEleBillaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount
     *
     * @mbggenerated Sat Jul 15 11:30:31 CST 2017
     */
    int updateByExample(@Param("record") VEleBillaccount record, @Param("example") VEleBillaccountExample example);
    
    /**
     * 批量插入
     * @author wangz
     * @param list
     * @return
     */
    int batchInsert(List<VEleBillaccount> list);
    
    /**
     * 查询数据库中最大数值的code
     * @author wangz
     * @param param
     * @return
     */
    Map<String,Object> queryMaxCode(Map<String,Object> param);
    
    /**
     * id更新审核状态
     * @author zhaol
     * @param map
     * 
     */
	void updateById(Map<String, Object> map);
	
	/**
	 * 查询报账点总数
     * @author SongJL
	 * @param map
	 */
	int selectBillaccountNum(Map<String, Object> map);

	Map<String, Object> queryContractMaxCode(Map<String, Object> param);
}