package com.xunge.dao.selfelec;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.xunge.model.selfelec.VEleBillaccountcontract;
import com.xunge.model.selfelec.VEleBillaccountcontractExample;

public interface VEleBillaccountcontractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccountcontract
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    int countByExample(VEleBillaccountcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccountcontract
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    int deleteByExample(VEleBillaccountcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccountcontract
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    int insert(VEleBillaccountcontract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccountcontract
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    int insertSelective(VEleBillaccountcontract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccountcontract
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    List<VEleBillaccountcontract> selectByExample(VEleBillaccountcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccountcontract
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    int updateByExampleSelective(@Param("record") VEleBillaccountcontract record, @Param("example") VEleBillaccountcontractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccountcontract
     *
     * @mbggenerated Sun Jul 23 13:23:41 CST 2017
     */
    int updateByExample(@Param("record") VEleBillaccountcontract record, @Param("example") VEleBillaccountcontractExample example);
    /**
     * 根据报账点id查询合同状态
     * @param billaccountId
     * @return
     */
    List<VEleBillaccountcontract> queryStateByBillaccountId(String billaccountId);
    /**
     * 根据报账点id查询合同缴费日期
     * @param billaccountId
     * @return
     */
    public String queryPaymentperiodIdByBillaccountId(String billaccountId);
    
    /**
     * 首页全查缴费记录信息
     * @param map
     * @return
     */
    public List<Map<String,String>> queryPaymentDetailByCondition(Map<String,Object>map);
}