package com.xunge.dao.selfelec;

import com.xunge.model.selfelec.VEleBaseresourceelectricmeter;
import com.xunge.model.selfelec.VEleBaseresourceelectricmeterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VEleBaseresourceelectricmeterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int countByExample(VEleBaseresourceelectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int deleteByExample(VEleBaseresourceelectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int insert(VEleBaseresourceelectricmeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int insertSelective(VEleBaseresourceelectricmeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    List<VEleBaseresourceelectricmeter> selectByExample(VEleBaseresourceelectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByExampleSelective(@Param("record") VEleBaseresourceelectricmeter record, @Param("example") VEleBaseresourceelectricmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_baseresourceelectricmeter
     *
     * @mbggenerated Sun Jul 02 03:52:13 CST 2017
     */
    int updateByExample(@Param("record") VEleBaseresourceelectricmeter record, @Param("example") VEleBaseresourceelectricmeterExample example);
}