package com.xunge.dao.selfelec;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.xunge.model.selfelec.VEleBillaccountPaymentInfo;
import com.xunge.model.selfelec.VEleBillaccountPaymentInfoExample;

public interface VEleBillaccountPaymentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount_payment_info
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    int countByExample(VEleBillaccountPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount_payment_info
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    int deleteByExample(VEleBillaccountPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount_payment_info
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    int insert(VEleBillaccountPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount_payment_info
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    int insertSelective(VEleBillaccountPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount_payment_info
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    List<VEleBillaccountPaymentInfo> selectByExample(VEleBillaccountPaymentInfoExample example);
    List<VEleBillaccountPaymentInfo> selectByExample(Map<String,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount_payment_info
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") VEleBillaccountPaymentInfo record, @Param("example") VEleBillaccountPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_ele_billaccount_payment_info
     *
     * @mbggenerated Sun Jul 23 03:57:00 CST 2017
     */
    int updateByExample(@Param("record") VEleBillaccountPaymentInfo record, @Param("example") VEleBillaccountPaymentInfoExample example);
    
    /**
     * 查询报账点审核页面
     * @param hashMaps
     * @return
     * @author xup
     */
	public List<VEleBillaccountPaymentInfo> queryEleBillaccountPayment(Map<String,Object> hashMaps);
	/**
	 * 删除明细账单
	 * @param map
	 * @return
	 * @author xup
	 */
	int deletePaymentDetail(Map<String,Object> map);
	
	  /**
     * @description 查询报账点及报账点缴费详细信息
     * @author yuefy
     * @date 创建时间：2017年9月21日
     */
	public List<VEleBillaccountPaymentInfo> selectBillamountPaymentDetails(Map<String,Object> map);
	/**
	 * 根据报账点编码查询此最大缴费期终的信息
	 * @param billaccountId
	 * @return
	 */
	public VEleBillaccountPaymentInfo queryMaxBillAccountEnded(String billaccountId);

}