package com.xunge.dao.basedata;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.xunge.model.DatPaymentperiod;
import com.xunge.model.DatPaymentperiodExample;

public interface DatPaymentperiodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_paymentperiod
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int countByExample(DatPaymentperiodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_paymentperiod
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int deleteByExample(DatPaymentperiodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_paymentperiod
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int deleteByPrimaryKey(String paymentperiodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_paymentperiod
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int insert(DatPaymentperiod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_paymentperiod
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int insertSelective(DatPaymentperiod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_paymentperiod
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    List<DatPaymentperiod> selectByExample(DatPaymentperiodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_paymentperiod
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    DatPaymentperiod selectByPrimaryKey(String paymentperiodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_paymentperiod
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") DatPaymentperiod record, @Param("example") DatPaymentperiodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_paymentperiod
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int updateByExample(@Param("record") DatPaymentperiod record, @Param("example") DatPaymentperiodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_paymentperiod
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int updateByPrimaryKeySelective(DatPaymentperiod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_paymentperiod
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    int updateByPrimaryKey(DatPaymentperiod record);
    

    String selectIdByValue(String value);
    
    List<Map<String, String>> getPaymentidlist();
}