package com.xunge.model.basedata;

import java.util.Date;

public class DatBasesite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String basesiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.reg_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_code
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String basesiteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_name
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String basesiteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_address
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String basesiteAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_type
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer basesiteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_state
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer basesiteState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_opendate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Date basesiteOpendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_stopdate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Date basesiteStopdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_belong
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer basesiteBelong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_property
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer basesiteProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_share
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer basesiteShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_longitude
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Long basesiteLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.basesite_latitude
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Long basesiteLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basesite.data_from
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer dataFrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_id
     *
     * @return the value of dat_basesite.basesite_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBasesiteId() {
        return basesiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_id
     *
     * @param basesiteId the value for dat_basesite.basesite_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteId(String basesiteId) {
        this.basesiteId = basesiteId == null ? null : basesiteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.reg_id
     *
     * @return the value of dat_basesite.reg_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.reg_id
     *
     * @param regId the value for dat_basesite.reg_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_code
     *
     * @return the value of dat_basesite.basesite_code
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBasesiteCode() {
        return basesiteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_code
     *
     * @param basesiteCode the value for dat_basesite.basesite_code
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteCode(String basesiteCode) {
        this.basesiteCode = basesiteCode == null ? null : basesiteCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_name
     *
     * @return the value of dat_basesite.basesite_name
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBasesiteName() {
        return basesiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_name
     *
     * @param basesiteName the value for dat_basesite.basesite_name
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteName(String basesiteName) {
        this.basesiteName = basesiteName == null ? null : basesiteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_address
     *
     * @return the value of dat_basesite.basesite_address
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBasesiteAddress() {
        return basesiteAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_address
     *
     * @param basesiteAddress the value for dat_basesite.basesite_address
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteAddress(String basesiteAddress) {
        this.basesiteAddress = basesiteAddress == null ? null : basesiteAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_type
     *
     * @return the value of dat_basesite.basesite_type
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBasesiteType() {
        return basesiteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_type
     *
     * @param basesiteType the value for dat_basesite.basesite_type
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteType(Integer basesiteType) {
        this.basesiteType = basesiteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_state
     *
     * @return the value of dat_basesite.basesite_state
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBasesiteState() {
        return basesiteState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_state
     *
     * @param basesiteState the value for dat_basesite.basesite_state
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteState(Integer basesiteState) {
        this.basesiteState = basesiteState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_opendate
     *
     * @return the value of dat_basesite.basesite_opendate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Date getBasesiteOpendate() {
        return basesiteOpendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_opendate
     *
     * @param basesiteOpendate the value for dat_basesite.basesite_opendate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteOpendate(Date basesiteOpendate) {
        this.basesiteOpendate = basesiteOpendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_stopdate
     *
     * @return the value of dat_basesite.basesite_stopdate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Date getBasesiteStopdate() {
        return basesiteStopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_stopdate
     *
     * @param basesiteStopdate the value for dat_basesite.basesite_stopdate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteStopdate(Date basesiteStopdate) {
        this.basesiteStopdate = basesiteStopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_belong
     *
     * @return the value of dat_basesite.basesite_belong
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBasesiteBelong() {
        return basesiteBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_belong
     *
     * @param basesiteBelong the value for dat_basesite.basesite_belong
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteBelong(Integer basesiteBelong) {
        this.basesiteBelong = basesiteBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_property
     *
     * @return the value of dat_basesite.basesite_property
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBasesiteProperty() {
        return basesiteProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_property
     *
     * @param basesiteProperty the value for dat_basesite.basesite_property
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteProperty(Integer basesiteProperty) {
        this.basesiteProperty = basesiteProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_share
     *
     * @return the value of dat_basesite.basesite_share
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBasesiteShare() {
        return basesiteShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_share
     *
     * @param basesiteShare the value for dat_basesite.basesite_share
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteShare(Integer basesiteShare) {
        this.basesiteShare = basesiteShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_longitude
     *
     * @return the value of dat_basesite.basesite_longitude
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Long getBasesiteLongitude() {
        return basesiteLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_longitude
     *
     * @param basesiteLongitude the value for dat_basesite.basesite_longitude
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteLongitude(Long basesiteLongitude) {
        this.basesiteLongitude = basesiteLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.basesite_latitude
     *
     * @return the value of dat_basesite.basesite_latitude
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Long getBasesiteLatitude() {
        return basesiteLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.basesite_latitude
     *
     * @param basesiteLatitude the value for dat_basesite.basesite_latitude
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteLatitude(Long basesiteLatitude) {
        this.basesiteLatitude = basesiteLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basesite.data_from
     *
     * @return the value of dat_basesite.data_from
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basesite.data_from
     *
     * @param dataFrom the value for dat_basesite.data_from
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setDataFrom(Integer dataFrom) {
        this.dataFrom = dataFrom;
    }
}