package com.xunge.model.basedata;

import java.util.Date;

public class DatBaseresource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String baseresourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.basesite_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String basesiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.prv_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String prvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.reg_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_type
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer baseresourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_category
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer baseresourceCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_cuid
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String baseresourceCuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_code
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String baseresourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_name
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String baseresourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_address
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String baseresourceAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_area
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Long baseresourceArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_opendate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Date baseresourceOpendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_stopdate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Date baseresourceStopdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.room_owner
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer roomOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.room_property
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer roomProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.room_share
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer roomShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_longitude
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Long baseresourceLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_latitude
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Long baseresourceLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.airconditioner_power
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Long airconditionerPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_state
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer baseresourceState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.baseresource_note
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String baseresourceNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_baseresource.data_from
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer dataFrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_id
     *
     * @return the value of dat_baseresource.baseresource_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBaseresourceId() {
        return baseresourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_id
     *
     * @param baseresourceId the value for dat_baseresource.baseresource_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceId(String baseresourceId) {
        this.baseresourceId = baseresourceId == null ? null : baseresourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.basesite_id
     *
     * @return the value of dat_baseresource.basesite_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBasesiteId() {
        return basesiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.basesite_id
     *
     * @param basesiteId the value for dat_baseresource.basesite_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasesiteId(String basesiteId) {
        this.basesiteId = basesiteId == null ? null : basesiteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.prv_id
     *
     * @return the value of dat_baseresource.prv_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getPrvId() {
        return prvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.prv_id
     *
     * @param prvId the value for dat_baseresource.prv_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setPrvId(String prvId) {
        this.prvId = prvId == null ? null : prvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.reg_id
     *
     * @return the value of dat_baseresource.reg_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.reg_id
     *
     * @param regId the value for dat_baseresource.reg_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_type
     *
     * @return the value of dat_baseresource.baseresource_type
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBaseresourceType() {
        return baseresourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_type
     *
     * @param baseresourceType the value for dat_baseresource.baseresource_type
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceType(Integer baseresourceType) {
        this.baseresourceType = baseresourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_category
     *
     * @return the value of dat_baseresource.baseresource_category
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBaseresourceCategory() {
        return baseresourceCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_category
     *
     * @param baseresourceCategory the value for dat_baseresource.baseresource_category
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceCategory(Integer baseresourceCategory) {
        this.baseresourceCategory = baseresourceCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_cuid
     *
     * @return the value of dat_baseresource.baseresource_cuid
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBaseresourceCuid() {
        return baseresourceCuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_cuid
     *
     * @param baseresourceCuid the value for dat_baseresource.baseresource_cuid
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceCuid(String baseresourceCuid) {
        this.baseresourceCuid = baseresourceCuid == null ? null : baseresourceCuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_code
     *
     * @return the value of dat_baseresource.baseresource_code
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBaseresourceCode() {
        return baseresourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_code
     *
     * @param baseresourceCode the value for dat_baseresource.baseresource_code
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceCode(String baseresourceCode) {
        this.baseresourceCode = baseresourceCode == null ? null : baseresourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_name
     *
     * @return the value of dat_baseresource.baseresource_name
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBaseresourceName() {
        return baseresourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_name
     *
     * @param baseresourceName the value for dat_baseresource.baseresource_name
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceName(String baseresourceName) {
        this.baseresourceName = baseresourceName == null ? null : baseresourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_address
     *
     * @return the value of dat_baseresource.baseresource_address
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBaseresourceAddress() {
        return baseresourceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_address
     *
     * @param baseresourceAddress the value for dat_baseresource.baseresource_address
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceAddress(String baseresourceAddress) {
        this.baseresourceAddress = baseresourceAddress == null ? null : baseresourceAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_area
     *
     * @return the value of dat_baseresource.baseresource_area
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Long getBaseresourceArea() {
        return baseresourceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_area
     *
     * @param baseresourceArea the value for dat_baseresource.baseresource_area
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceArea(Long baseresourceArea) {
        this.baseresourceArea = baseresourceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_opendate
     *
     * @return the value of dat_baseresource.baseresource_opendate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Date getBaseresourceOpendate() {
        return baseresourceOpendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_opendate
     *
     * @param baseresourceOpendate the value for dat_baseresource.baseresource_opendate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceOpendate(Date baseresourceOpendate) {
        this.baseresourceOpendate = baseresourceOpendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_stopdate
     *
     * @return the value of dat_baseresource.baseresource_stopdate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Date getBaseresourceStopdate() {
        return baseresourceStopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_stopdate
     *
     * @param baseresourceStopdate the value for dat_baseresource.baseresource_stopdate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceStopdate(Date baseresourceStopdate) {
        this.baseresourceStopdate = baseresourceStopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.room_owner
     *
     * @return the value of dat_baseresource.room_owner
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getRoomOwner() {
        return roomOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.room_owner
     *
     * @param roomOwner the value for dat_baseresource.room_owner
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setRoomOwner(Integer roomOwner) {
        this.roomOwner = roomOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.room_property
     *
     * @return the value of dat_baseresource.room_property
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getRoomProperty() {
        return roomProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.room_property
     *
     * @param roomProperty the value for dat_baseresource.room_property
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setRoomProperty(Integer roomProperty) {
        this.roomProperty = roomProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.room_share
     *
     * @return the value of dat_baseresource.room_share
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getRoomShare() {
        return roomShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.room_share
     *
     * @param roomShare the value for dat_baseresource.room_share
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setRoomShare(Integer roomShare) {
        this.roomShare = roomShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_longitude
     *
     * @return the value of dat_baseresource.baseresource_longitude
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Long getBaseresourceLongitude() {
        return baseresourceLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_longitude
     *
     * @param baseresourceLongitude the value for dat_baseresource.baseresource_longitude
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceLongitude(Long baseresourceLongitude) {
        this.baseresourceLongitude = baseresourceLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_latitude
     *
     * @return the value of dat_baseresource.baseresource_latitude
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Long getBaseresourceLatitude() {
        return baseresourceLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_latitude
     *
     * @param baseresourceLatitude the value for dat_baseresource.baseresource_latitude
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceLatitude(Long baseresourceLatitude) {
        this.baseresourceLatitude = baseresourceLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.airconditioner_power
     *
     * @return the value of dat_baseresource.airconditioner_power
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Long getAirconditionerPower() {
        return airconditionerPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.airconditioner_power
     *
     * @param airconditionerPower the value for dat_baseresource.airconditioner_power
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setAirconditionerPower(Long airconditionerPower) {
        this.airconditionerPower = airconditionerPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_state
     *
     * @return the value of dat_baseresource.baseresource_state
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBaseresourceState() {
        return baseresourceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_state
     *
     * @param baseresourceState the value for dat_baseresource.baseresource_state
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceState(Integer baseresourceState) {
        this.baseresourceState = baseresourceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.baseresource_note
     *
     * @return the value of dat_baseresource.baseresource_note
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBaseresourceNote() {
        return baseresourceNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.baseresource_note
     *
     * @param baseresourceNote the value for dat_baseresource.baseresource_note
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceNote(String baseresourceNote) {
        this.baseresourceNote = baseresourceNote == null ? null : baseresourceNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_baseresource.data_from
     *
     * @return the value of dat_baseresource.data_from
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_baseresource.data_from
     *
     * @param dataFrom the value for dat_baseresource.data_from
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setDataFrom(Integer dataFrom) {
        this.dataFrom = dataFrom;
    }
}