package com.xunge.model.basedata;

import java.util.Date;

public class DatBasestation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String basestationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.prv_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String prvId;
    
    private String regId;
    private String pregId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.baseresource_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String baseresourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.baseresource_cuid
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String baseresourceCuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_code
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String basestationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_name
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String basestationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_category
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer basestationCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_type
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer basestationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_opendate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Date basestationOpendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_stopdate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Date basestationStopdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_vendor
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer basestationVendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_model
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String basestationModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_power
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Long basestationPower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_state
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer basestationState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_carrier
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer basestationCarrier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.basestation_covertype
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer basestationCovertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_basestation.data_from
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer dataFrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_id
     *
     * @return the value of dat_basestation.basestation_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBasestationId() {
        return basestationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_id
     *
     * @param basestationId the value for dat_basestation.basestation_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationId(String basestationId) {
        this.basestationId = basestationId == null ? null : basestationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.prv_id
     *
     * @return the value of dat_basestation.prv_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getPrvId() {
        return prvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.prv_id
     *
     * @param prvId the value for dat_basestation.prv_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setPrvId(String prvId) {
        this.prvId = prvId == null ? null : prvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.baseresource_id
     *
     * @return the value of dat_basestation.baseresource_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBaseresourceId() {
        return baseresourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.baseresource_id
     *
     * @param baseresourceId the value for dat_basestation.baseresource_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceId(String baseresourceId) {
        this.baseresourceId = baseresourceId == null ? null : baseresourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.baseresource_cuid
     *
     * @return the value of dat_basestation.baseresource_cuid
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBaseresourceCuid() {
        return baseresourceCuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.baseresource_cuid
     *
     * @param baseresourceCuid the value for dat_basestation.baseresource_cuid
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBaseresourceCuid(String baseresourceCuid) {
        this.baseresourceCuid = baseresourceCuid == null ? null : baseresourceCuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_code
     *
     * @return the value of dat_basestation.basestation_code
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBasestationCode() {
        return basestationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_code
     *
     * @param basestationCode the value for dat_basestation.basestation_code
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationCode(String basestationCode) {
        this.basestationCode = basestationCode == null ? null : basestationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_name
     *
     * @return the value of dat_basestation.basestation_name
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBasestationName() {
        return basestationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_name
     *
     * @param basestationName the value for dat_basestation.basestation_name
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationName(String basestationName) {
        this.basestationName = basestationName == null ? null : basestationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_category
     *
     * @return the value of dat_basestation.basestation_category
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBasestationCategory() {
        return basestationCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_category
     *
     * @param basestationCategory the value for dat_basestation.basestation_category
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationCategory(Integer basestationCategory) {
        this.basestationCategory = basestationCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_type
     *
     * @return the value of dat_basestation.basestation_type
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBasestationType() {
        return basestationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_type
     *
     * @param basestationType the value for dat_basestation.basestation_type
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationType(Integer basestationType) {
        this.basestationType = basestationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_opendate
     *
     * @return the value of dat_basestation.basestation_opendate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Date getBasestationOpendate() {
        return basestationOpendate;
    }
    
    public String getRegId() {
		return regId;
	}

	public void setRegId(String regId) {
		this.regId = regId;
	}

	public String getPregId() {
		return pregId;
	}

	public void setPregId(String pregId) {
		this.pregId = pregId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_opendate
     *
     * @param basestationOpendate the value for dat_basestation.basestation_opendate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationOpendate(Date basestationOpendate) {
        this.basestationOpendate = basestationOpendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_stopdate
     *
     * @return the value of dat_basestation.basestation_stopdate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Date getBasestationStopdate() {
        return basestationStopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_stopdate
     *
     * @param basestationStopdate the value for dat_basestation.basestation_stopdate
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationStopdate(Date basestationStopdate) {
        this.basestationStopdate = basestationStopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_vendor
     *
     * @return the value of dat_basestation.basestation_vendor
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBasestationVendor() {
        return basestationVendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_vendor
     *
     * @param basestationVendor the value for dat_basestation.basestation_vendor
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationVendor(Integer basestationVendor) {
        this.basestationVendor = basestationVendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_model
     *
     * @return the value of dat_basestation.basestation_model
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getBasestationModel() {
        return basestationModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_model
     *
     * @param basestationModel the value for dat_basestation.basestation_model
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationModel(String basestationModel) {
        this.basestationModel = basestationModel == null ? null : basestationModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_power
     *
     * @return the value of dat_basestation.basestation_power
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Long getBasestationPower() {
        return basestationPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_power
     *
     * @param basestationPower the value for dat_basestation.basestation_power
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationPower(Long basestationPower) {
        this.basestationPower = basestationPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_state
     *
     * @return the value of dat_basestation.basestation_state
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBasestationState() {
        return basestationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_state
     *
     * @param basestationState the value for dat_basestation.basestation_state
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationState(Integer basestationState) {
        this.basestationState = basestationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_carrier
     *
     * @return the value of dat_basestation.basestation_carrier
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBasestationCarrier() {
        return basestationCarrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_carrier
     *
     * @param basestationCarrier the value for dat_basestation.basestation_carrier
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationCarrier(Integer basestationCarrier) {
        this.basestationCarrier = basestationCarrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.basestation_covertype
     *
     * @return the value of dat_basestation.basestation_covertype
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getBasestationCovertype() {
        return basestationCovertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.basestation_covertype
     *
     * @param basestationCovertype the value for dat_basestation.basestation_covertype
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setBasestationCovertype(Integer basestationCovertype) {
        this.basestationCovertype = basestationCovertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_basestation.data_from
     *
     * @return the value of dat_basestation.data_from
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_basestation.data_from
     *
     * @param dataFrom the value for dat_basestation.data_from
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setDataFrom(Integer dataFrom) {
        this.dataFrom = dataFrom;
    }
}