package com.xunge.model.basedata;

import java.math.BigDecimal;
import java.util.Date;

public class DatElectricmeter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.meter_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private String meterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.prv_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private String prvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.prv_sname
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private String prvSname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.preg_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private String pregId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.preg_name
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private String pregName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.reg_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.reg_name
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private String regName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.billaccount_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private String billaccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.meter_code
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private String meterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.initial_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private BigDecimal initialValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private BigDecimal upperValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.flat_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private BigDecimal flatValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.peak_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private BigDecimal peakValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.top_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private BigDecimal topValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.valley_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private BigDecimal valleyValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.flat_upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private BigDecimal flatUpperValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.peak_upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private BigDecimal peakUpperValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.valley_upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private BigDecimal valleyUpperValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.top_upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private BigDecimal topUpperValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.meter_type
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private Integer meterType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.electricmeter_multiply
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private BigDecimal electricmeterMultiply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.account_number
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private String accountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.install_date
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private Date installDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.meter_state
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private Integer meterState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.is_share
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private Integer isShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.meter_note
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private String meterNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_electricmeter.data_from
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    private Integer dataFrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.meter_id
     *
     * @return the value of dat_electricmeter.meter_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public String getMeterId() {
        return meterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.meter_id
     *
     * @param meterId the value for dat_electricmeter.meter_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setMeterId(String meterId) {
        this.meterId = meterId == null ? null : meterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.prv_id
     *
     * @return the value of dat_electricmeter.prv_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public String getPrvId() {
        return prvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.prv_id
     *
     * @param prvId the value for dat_electricmeter.prv_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setPrvId(String prvId) {
        this.prvId = prvId == null ? null : prvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.prv_sname
     *
     * @return the value of dat_electricmeter.prv_sname
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public String getPrvSname() {
        return prvSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.prv_sname
     *
     * @param prvSname the value for dat_electricmeter.prv_sname
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setPrvSname(String prvSname) {
        this.prvSname = prvSname == null ? null : prvSname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.preg_id
     *
     * @return the value of dat_electricmeter.preg_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public String getPregId() {
        return pregId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.preg_id
     *
     * @param pregId the value for dat_electricmeter.preg_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setPregId(String pregId) {
        this.pregId = pregId == null ? null : pregId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.preg_name
     *
     * @return the value of dat_electricmeter.preg_name
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public String getPregName() {
        return pregName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.preg_name
     *
     * @param pregName the value for dat_electricmeter.preg_name
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setPregName(String pregName) {
        this.pregName = pregName == null ? null : pregName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.reg_id
     *
     * @return the value of dat_electricmeter.reg_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.reg_id
     *
     * @param regId the value for dat_electricmeter.reg_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.reg_name
     *
     * @return the value of dat_electricmeter.reg_name
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public String getRegName() {
        return regName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.reg_name
     *
     * @param regName the value for dat_electricmeter.reg_name
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setRegName(String regName) {
        this.regName = regName == null ? null : regName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.billaccount_id
     *
     * @return the value of dat_electricmeter.billaccount_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public String getBillaccountId() {
        return billaccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.billaccount_id
     *
     * @param billaccountId the value for dat_electricmeter.billaccount_id
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setBillaccountId(String billaccountId) {
        this.billaccountId = billaccountId == null ? null : billaccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.meter_code
     *
     * @return the value of dat_electricmeter.meter_code
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public String getMeterCode() {
        return meterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.meter_code
     *
     * @param meterCode the value for dat_electricmeter.meter_code
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setMeterCode(String meterCode) {
        this.meterCode = meterCode == null ? null : meterCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.initial_value
     *
     * @return the value of dat_electricmeter.initial_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public BigDecimal getInitialValue() {
        return initialValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.initial_value
     *
     * @param initialValue the value for dat_electricmeter.initial_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setInitialValue(BigDecimal initialValue) {
        this.initialValue = initialValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.upper_value
     *
     * @return the value of dat_electricmeter.upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public BigDecimal getUpperValue() {
        return upperValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.upper_value
     *
     * @param upperValue the value for dat_electricmeter.upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setUpperValue(BigDecimal upperValue) {
        this.upperValue = upperValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.flat_value
     *
     * @return the value of dat_electricmeter.flat_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public BigDecimal getFlatValue() {
        return flatValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.flat_value
     *
     * @param flatValue the value for dat_electricmeter.flat_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setFlatValue(BigDecimal flatValue) {
        this.flatValue = flatValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.peak_value
     *
     * @return the value of dat_electricmeter.peak_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public BigDecimal getPeakValue() {
        return peakValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.peak_value
     *
     * @param peakValue the value for dat_electricmeter.peak_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setPeakValue(BigDecimal peakValue) {
        this.peakValue = peakValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.top_value
     *
     * @return the value of dat_electricmeter.top_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public BigDecimal getTopValue() {
        return topValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.top_value
     *
     * @param topValue the value for dat_electricmeter.top_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setTopValue(BigDecimal topValue) {
        this.topValue = topValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.valley_value
     *
     * @return the value of dat_electricmeter.valley_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public BigDecimal getValleyValue() {
        return valleyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.valley_value
     *
     * @param valleyValue the value for dat_electricmeter.valley_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setValleyValue(BigDecimal valleyValue) {
        this.valleyValue = valleyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.flat_upper_value
     *
     * @return the value of dat_electricmeter.flat_upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public BigDecimal getFlatUpperValue() {
        return flatUpperValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.flat_upper_value
     *
     * @param flatUpperValue the value for dat_electricmeter.flat_upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setFlatUpperValue(BigDecimal flatUpperValue) {
        this.flatUpperValue = flatUpperValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.peak_upper_value
     *
     * @return the value of dat_electricmeter.peak_upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public BigDecimal getPeakUpperValue() {
        return peakUpperValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.peak_upper_value
     *
     * @param peakUpperValue the value for dat_electricmeter.peak_upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setPeakUpperValue(BigDecimal peakUpperValue) {
        this.peakUpperValue = peakUpperValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.valley_upper_value
     *
     * @return the value of dat_electricmeter.valley_upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public BigDecimal getValleyUpperValue() {
        return valleyUpperValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.valley_upper_value
     *
     * @param valleyUpperValue the value for dat_electricmeter.valley_upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setValleyUpperValue(BigDecimal valleyUpperValue) {
        this.valleyUpperValue = valleyUpperValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.top_upper_value
     *
     * @return the value of dat_electricmeter.top_upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public BigDecimal getTopUpperValue() {
        return topUpperValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.top_upper_value
     *
     * @param topUpperValue the value for dat_electricmeter.top_upper_value
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setTopUpperValue(BigDecimal topUpperValue) {
        this.topUpperValue = topUpperValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.meter_type
     *
     * @return the value of dat_electricmeter.meter_type
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public Integer getMeterType() {
        return meterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.meter_type
     *
     * @param meterType the value for dat_electricmeter.meter_type
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setMeterType(Integer meterType) {
        this.meterType = meterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.electricmeter_multiply
     *
     * @return the value of dat_electricmeter.electricmeter_multiply
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public BigDecimal getElectricmeterMultiply() {
        return electricmeterMultiply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.electricmeter_multiply
     *
     * @param electricmeterMultiply the value for dat_electricmeter.electricmeter_multiply
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setElectricmeterMultiply(BigDecimal electricmeterMultiply) {
        this.electricmeterMultiply = electricmeterMultiply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.account_number
     *
     * @return the value of dat_electricmeter.account_number
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.account_number
     *
     * @param accountNumber the value for dat_electricmeter.account_number
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber == null ? null : accountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.install_date
     *
     * @return the value of dat_electricmeter.install_date
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public Date getInstallDate() {
        return installDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.install_date
     *
     * @param installDate the value for dat_electricmeter.install_date
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setInstallDate(Date installDate) {
        this.installDate = installDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.meter_state
     *
     * @return the value of dat_electricmeter.meter_state
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public Integer getMeterState() {
        return meterState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.meter_state
     *
     * @param meterState the value for dat_electricmeter.meter_state
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setMeterState(Integer meterState) {
        this.meterState = meterState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.is_share
     *
     * @return the value of dat_electricmeter.is_share
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public Integer getIsShare() {
        return isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.is_share
     *
     * @param isShare the value for dat_electricmeter.is_share
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setIsShare(Integer isShare) {
        this.isShare = isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.meter_note
     *
     * @return the value of dat_electricmeter.meter_note
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public String getMeterNote() {
        return meterNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.meter_note
     *
     * @param meterNote the value for dat_electricmeter.meter_note
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setMeterNote(String meterNote) {
        this.meterNote = meterNote == null ? null : meterNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_electricmeter.data_from
     *
     * @return the value of dat_electricmeter.data_from
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public Integer getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_electricmeter.data_from
     *
     * @param dataFrom the value for dat_electricmeter.data_from
     *
     * @mbggenerated Mon Jul 24 18:13:33 CST 2017
     */
    public void setDataFrom(Integer dataFrom) {
        this.dataFrom = dataFrom;
    }
}