package com.xunge.model.basedata;

public class DatPaymentperiod {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_paymentperiod.paymentperiod_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String paymentperiodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_paymentperiod.paymentperiod_name
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private String paymentperiodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_paymentperiod.paymentperiod_value
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Long paymentperiodValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_paymentperiod.paymentperiod_unit
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer paymentperiodUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_paymentperiod.paymentperiod_order
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer paymentperiodOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_paymentperiod.paymentperiod_state
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    private Integer paymentperiodState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_paymentperiod.paymentperiod_id
     *
     * @return the value of dat_paymentperiod.paymentperiod_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getPaymentperiodId() {
        return paymentperiodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_paymentperiod.paymentperiod_id
     *
     * @param paymentperiodId the value for dat_paymentperiod.paymentperiod_id
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setPaymentperiodId(String paymentperiodId) {
        this.paymentperiodId = paymentperiodId == null ? null : paymentperiodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_paymentperiod.paymentperiod_name
     *
     * @return the value of dat_paymentperiod.paymentperiod_name
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public String getPaymentperiodName() {
        return paymentperiodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_paymentperiod.paymentperiod_name
     *
     * @param paymentperiodName the value for dat_paymentperiod.paymentperiod_name
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setPaymentperiodName(String paymentperiodName) {
        this.paymentperiodName = paymentperiodName == null ? null : paymentperiodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_paymentperiod.paymentperiod_value
     *
     * @return the value of dat_paymentperiod.paymentperiod_value
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Long getPaymentperiodValue() {
        return paymentperiodValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_paymentperiod.paymentperiod_value
     *
     * @param paymentperiodValue the value for dat_paymentperiod.paymentperiod_value
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setPaymentperiodValue(Long paymentperiodValue) {
        this.paymentperiodValue = paymentperiodValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_paymentperiod.paymentperiod_unit
     *
     * @return the value of dat_paymentperiod.paymentperiod_unit
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getPaymentperiodUnit() {
        return paymentperiodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_paymentperiod.paymentperiod_unit
     *
     * @param paymentperiodUnit the value for dat_paymentperiod.paymentperiod_unit
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setPaymentperiodUnit(Integer paymentperiodUnit) {
        this.paymentperiodUnit = paymentperiodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_paymentperiod.paymentperiod_order
     *
     * @return the value of dat_paymentperiod.paymentperiod_order
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getPaymentperiodOrder() {
        return paymentperiodOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_paymentperiod.paymentperiod_order
     *
     * @param paymentperiodOrder the value for dat_paymentperiod.paymentperiod_order
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setPaymentperiodOrder(Integer paymentperiodOrder) {
        this.paymentperiodOrder = paymentperiodOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_paymentperiod.paymentperiod_state
     *
     * @return the value of dat_paymentperiod.paymentperiod_state
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public Integer getPaymentperiodState() {
        return paymentperiodState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_paymentperiod.paymentperiod_state
     *
     * @param paymentperiodState the value for dat_paymentperiod.paymentperiod_state
     *
     * @mbggenerated Fri Jun 23 16:48:59 CST 2017
     */
    public void setPaymentperiodState(Integer paymentperiodState) {
        this.paymentperiodState = paymentperiodState;
    }
}